# Importing Data from API :

In [2]:
# importing libraries :

import pandas as pd 
import requests

In [6]:
# Creating the variable response where the json data through the api call is getting stored!

response = requests.get('https://api.themoviedb.org/3/tv/top_rated?api_key=2907a3004f657179e96619acd03cc0f8')

In [7]:
response.json()

{'page': 1,
 'results': [{'adult': False,
   'backdrop_path': '/vyG93jhmPL7tBIhRtCLa5mdBKob.jpg',
   'genre_ids': [10759, 18, 35],
   'id': 276161,
   'origin_country': ['KR'],
   'original_language': 'ko',
   'original_name': '참교육',
   'overview': 'An inspector from the Educational Rights Protection Bureau (ERPB) who is authorized by the government to use physical intervention and unconventional methods to discipline delinquent students and reform the educational system.',
   'popularity': 67.8504,
   'poster_path': '/fMECSPrTmRClSViMsXFYmiYIcWP.jpg',
   'first_air_date': '2026-06-05',
   'softcore': False,
   'name': 'Teach You a Lesson',
   'vote_average': 9.42,
   'vote_count': 809},
  {'adult': False,
   'backdrop_path': '/wh5agdl3b7fqC7mSjsCkHx4fMAs.jpg',
   'genre_ids': [37, 18],
   'id': 299167,
   'origin_country': ['US'],
   'original_language': 'en',
   'original_name': 'Dutton Ranch',
   'overview': 'Rip Wheeler and Beth Dutton gamble everything on a new life in South Texas, but the promise of building a future far from the ghosts of Yellowstone quickly collides with brutal new realities and a rival ranch that will stop at nothing to protect its empire.',
   'popularity': 75.4352,
   'poster_path': '/xsiecCxd8lkcAluw0wWwbW5CwSv.jpg',
   'first_air_date': '2026-05-15',
   'softcore': False,
   'name': 'Dutton Ranch',
   'vote_average': 9.166,
   'vote_count': 540},
  {'adult': False,
   'backdrop_path': '/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg',
   'genre_ids': [18, 80],
   'id': 1396,
   'origin_country': ['US'],
   'original_language': 'en',
   'original_name': 'Breaking Bad',
   'overview': "Walter White, a New Mexico chemistry teacher, is diagnosed with Stage III cancer and given a prognosis of only two years left to live. He becomes filled with a sense of fearlessness and an unrelenting desire to secure his family's financial future at any cost as he enters the dangerous world of drugs and crime.",
   'popularity': 148.9727,
   'poster_path': '/anFx9aTOOYqgS3v7x3R84Kz67ly.jpg',
   'first_air_date': '2008-01-20',
   'softcore': False,
   'name': 'Breaking Bad',
   'vote_average': 8.949,
   'vote_count': 18419},
  {'adult': False,
   'backdrop_path': '/3ANXZWhhcqPAh0q6nRZ979TIwxC.jpg',
   'genre_ids': [18],
   'id': 273240,
   'origin_country': ['US'],
   'original_language': 'en',
   'original_name': 'Off Campus',
   'overview': 'Hannah Wells tutors hockey captain Garrett Graham to win over her crush. Their deal becomes real connection as they face their pasts. Friends Logan, Dean, Tucker, and Allie navigate college life and love.',
   'popularity': 77.7385,
   'poster_path': '/tcPc5ZMBO4y2BtCJMe3o2nwZb2B.jpg',
   'first_air_date': '2026-05-13',
   'softcore': False,
   'name': 'Off Campus',
   'vote_average': 8.902,
   'vote_count': 791},
  {'adult': False,
   'backdrop_path': '/810mXC0xkxXVtoKIPGGVgO9PuLh.jpg',
   'genre_ids': [10759, 35, 10765, 18],
   'id': 259837,
   'origin_country': ['KR'],
   'original_language': 'ko',
   'original_name': '원더풀스',
   'overview': 'A goofy group of townies stumbles into superpowers and fights rising evil as doomsday panic grows in this wild, turn-of-the-century action comedy.',
   'popularity': 22.8965,
   'poster_path': '/jj7AYkz2OLRDL1wfJmjTXyWQ5I4.jpg',
   'first_air_date': '2026-05-15',
   'softcore': False,
   'name': 'The WONDERfools',
   'vote_average': 8.9,
   'vote_count': 245},
  {'adult': False,
   'backdrop_path': '/TxicZcsiP9VHYXMYHm4IEHnwv9.jpg',
   'genre_ids': [35, 10765, 10751],
   'id': 245026,
   'origin_country': ['US'],
   'original_language': 'en',
   'original_name': 'Wizards Beyond Waverly Place',
   'overview': "Justin Russo has chosen to lead a normal, mortal life with his family, Giada, Roman and Milo. But when Justin's sister Alex brings Billie to his home seeking help, Justin realizes he must dust off his magical skills to mentor the wizard-in-training while also juggling his everyday responsibilities — and safeguarding the future of the Wizard World.",
   'popularity': 34.1248,
   'poster_path': '/5hrBpjFzIqmN9k7QxEC610gwZGw.jpg',
   'first_air_date': '2024-10-29',
   'softcore': False,
   'name': 'Wizards Beyond Waverly Place',
   'vote_average': 8.9,
   'vote_count': 201},
  {'adult': False,
   'backdrop_path': '/rBOnrVlck7BIlGeWVlzYiZeg4l2.jpg',
   'genre_ids': [16, 10759, 18, 10765],
   'id': 209867,
   'origin_country': ['JP'],
   'original_language': 'ja',
   'original_name': '葬送のフリーレン',
   'overview': 'After the party of heroes defeated the Demon King, they restored peace to the land and returned to lives of solitude.  Generations pass, and the elven mage Frieren comes face to face with humanity’s mortality. She takes on a new apprentice and promises to fulfill old friends’ dying wishes. Can an elven mind make peace with the nature of life and death? Frieren embarks on her quest to find out.',
   'popularity': 86.0829,
   'poster_path': '/dqZENchTd7lp5zht7BdlqM7RBhD.jpg',
   'first_air_date': '2023-09-29',
   'softcore': False,
   'name': "Frieren: Beyond Journey's End",
   'vote_average': 8.802,
   'vote_count': 932},
  {'adult': False,
   'backdrop_path': '/3siv3RaQrdr2tQiv9jHq71sLlzo.jpg',
   'genre_ids': [10759, 10751, 18],
   'id': 85077,
   'origin_country': ['US'],
   'original_language': 'en',
   'original_name': 'The Chosen',
   'overview': 'The life of Christ through the eyes of those who encountered him.',
   'popularity': 62.3312,
   'poster_path': '/dqVUFuNrMFWt7uGNWlpo91VKYOI.jpg',
   'first_air_date': '2019-04-21',
   'softcore': False,
   'name': 'The Chosen',
   'vote_average': 8.794,
   'vote_count': 952},
  {'adult': False,
   'backdrop_path': '/7oBGhqJIghRBvOwo5Qe0yM0cnMc.jpg',
   'genre_ids': [16, 10759, 10765],
   'id': 246,
   'origin_country': ['US'],
   'original_language': 'en',
   'original_name': 'Avatar: The Last Airbender',
   'overview': 'In a war-torn world of elemental magic, a young boy reawakens to undertake a dangerous mystic quest to fulfill his destiny as the Avatar, and bring peace to the world.',
   'popularity': 30.8563,
   'poster_path': '/yaGt4GIutpbXHsv48tWceWg6s56.jpg',
   'first_air_date': '2005-02-21',
   'softcore': False,
   'name': 'Avatar: The Last Airbender',
   'vote_average': 8.778,
   'vote_count': 5051},
  {'adult': False,
   'backdrop_path': '/a9qlroMOHewiDsUR93PYMVfpbF5.jpg',
   'genre_ids': [18],
   'id': 219246,
   'origin_country': ['KR'],
   'original_language': 'ko',
   'original_name': '폭싹 속았수다',
   'overview': "In Jeju, a spirited girl and a steadfast boy's island story blossoms into a lifelong tale of setbacks and triumphs — proving love endures across time.",
   'popularity': 25.7212,
   'poster_path': '/1VC3sEFxYXYDqQUCAnvWfUsYg1s.jpg',
   'first_air_date': '2025-03-07',
   'softcore': False,
   'name': 'When Life Gives You Tangerines',
   'vote_average': 8.763,
   'vote_count': 570},
  {'adult': False,
   'backdrop_path': '/wgmikRStgBbrzjxFVe5rhFlpL2R.jpg',
   'genre_ids': [35],
   'id': 64010,
   'origin_country': ['KR'],
   'original_language': 'ko',
   'original_name': '응답하라 1988',
   'overview': 'Take a nostalgic trip back to the late 1980s through the lives of five families and their five teenage kids living in a small neighbourhood in Seoul.',
   'popularity': 16.305,
   'poster_path': '/i3xQJlQRff4k5IMEY55l4iKaKl3.jpg',
   'first_air_date': '2015-11-06',
   'softcore': False,
   'name': 'Reply 1988',
   'vote_average': 8.759,
   'vote_count': 222},
  {'adult': False,
   'backdrop_path': '/q8eejQcg1bAqImEV8jh8RtBD4uH.jpg',
   'genre_ids': [16, 10759, 10765],
   'id': 94605,
   'origin_country': ['US'],
   'original_language': 'en',
   'original_name': 'Arcane',
   'overview': 'Amid the stark discord of twin cities Piltover and Zaun, two sisters fight on rival sides of a war between magic technologies and clashing convictions.',
   'popularity': 35.1375,
   'poster_path': '/fqldf2t8ztc9aiwn3k6mlX3tvRT.jpg',
   'first_air_date': '2021-11-06',
   'softcore': False,
   'name': 'Arcane',
   'vote_average': 8.8,
   'vote_count': 6106},
  {'adult': False,
   'backdrop_path': '/2rmK7mnchw9Xr3XdiTFSxTTLXqv.jpg',
   'genre_ids': [10759, 35, 16],
   'id': 37854,
   'origin_country': ['JP'],
   'original_language': 'ja',
   'original_name': 'ワンピース',
   'overview': 'Years ago, the fearsome Pirate King, Gol D. Roger was executed leaving a huge pile of treasure and the famous "One Piece" behind. Whoever claims the "One Piece" will be named the new King of the Pirates.\n\nMonkey D. Luffy, a boy who consumed a "Devil Fruit," decides to follow in the footsteps of his idol, the pirate Shanks, and find the One Piece. It helps, of course, that his body has the properties of rubber and that he\'s surrounded by a bevy of skilled fighters and thieves to help him along the way.\n\nLuffy will do anything to get the One Piece and become King of the Pirates!',
   'popularity': 49.6344,
   'poster_path': '/dB4EDhre2dsC2kxYDavyKWqLQwi.jpg',
   'first_air_date': '1999-10-20',
   'softcore': False,
   'name': 'One Piece',
   'vote_average': 8.75,
   'vote_count': 5487},
  {'adult': False,
   'backdrop_path': '/iS76c29IrS3lKI2X5CFySguiAWU.jpg',
   'genre_ids': [18],
   'id': 301507,
   'origin_country': ['CA'],
   'original_language': 'en',
   'original_name': 'Heated Rivalry',
   'overview': 'Two of the biggest stars in Major League Hockey are bound by ambition, rivalry, and a magnetic pull neither of them fully understands. What begins as a secret fling between two fresh faced rookies evolves into a years-long journey of love, denial, and self-discovery. Over the next eight years, as they chase glory on the ice, they struggle to navigate their feelings for each other. Torn between the sport they live for and the love they can’t ignore, they must decide if there’s room in their fiercely competitive world for something as fragile – and powerful – as real love.',
   'popularity': 33.8137,
   'poster_path': '/3YCKbtAkYWCMDLHvkUjGhG7eWoS.jpg',
   'first_air_date': '2025-11-28',
   'softcore': False,
   'name': 'Heated Rivalry',
   'vote_average': 8.738,
   'vote_count': 582},
  {'adult': False,
   'backdrop_path': '/jmV6NIzZxGzRoljFPwao6sh4Nny.jpg',
   'genre_ids': [18, 35],
   'id': 259666,
   'origin_country': ['MX'],
   'original_language': 'es',
   'original_name': 'Nadie nos va a extrañar',
   'overview': "It's the '90s, and five losers run an illegal business at their high school. They sell homework and assignments to their classmates. The advantage is that no one ever suspects the nerds. Their business brings them money and popularity. But hormones and an unexpected death threaten to ruin everything. If the business collapses, their futures and their friendships are at risk.",
   'popularity': 42.0105,
   'poster_path': '/5U3WiAz67fJn5gnvFk4zOJAx9Sc.jpg',
   'first_air_date': '2024-08-09',
   'softcore': False,
   'name': 'No One Will Miss Us',
   'vote_average': 8.7,
   'vote_count': 351},
  {'adult': False,
   'backdrop_path': '/z3BkMbCy5ajZPMyKEUwsPHuz2cV.jpg',
   'genre_ids': [18],
   'id': 250307,
   'origin_country': ['US'],
   'original_language': 'en',
   'original_name': 'The Pitt',
   'overview': "The staff of Pittsburgh's Trauma Medical Center work around the clock to save lives in an overcrowded and underfunded emergency department.",
   'popularity': 85.638,
   'poster_path': '/kvFSpESyBZMjaeOJDx7RS3P1jey.jpg',
   'first_air_date': '2025-01-09',
   'softcore': False,
   'name': 'The Pitt',
   'vote_average': 8.722,
   'vote_count': 910},
  {'adult': False,
   'backdrop_path': '/3URK0z9PzpVNJrGE7XOuyy6KFzk.jpg',
   'genre_ids': [18],
   'id': 87108,
   'origin_country': ['US'],
   'original_language': 'en',
   'original_name': 'Chernobyl',
   'overview': 'The true story of one of the worst man-made catastrophes in history: the catastrophic nuclear accident at Chernobyl. A tale of the brave men and women who sacrificed to save Europe from unimaginable disaster.',
   'popularity': 40.9514,
   'poster_path': '/hlLXt2tOPT6RRnjiUmoxyG1LTFi.jpg',
   'first_air_date': '2019-05-06',
   'softcore': False,
   'name': 'Chernobyl',
   'vote_average': 8.722,
   'vote_count': 8179},
  {'adult': False,
   'backdrop_path': '/2UG177tWHy7xRmMKWJHB7nAUmKd.jpg',
   'genre_ids': [16, 10759, 10765, 18],
   'id': 31911,
   'origin_country': ['JP'],
   'original_language': 'ja',
   'original_name': '鋼の錬金術師 FULLMETAL ALCHEMIST',
   'overview': 'Disregard for alchemy’s laws ripped half of Edward Elric’s limbs from his body and left his brother Alphonse’s soul clinging to a suit of armor. To restore what was lost, the brothers seek the Philosopher’s Stone. Enemies and allies – the corrupt military, the Homunculi, and foreign alchemists – will alter the Elric brothers course, but their purpose will remain unchanged and their bond unbreakable.',
   'popularity': 47.2786,
   'poster_path': '/5ZFUEOULaVml7pQuXxhpR2SmVUw.jpg',
   'first_air_date': '2009-04-05',
   'softcore': False,
   'name': 'Fullmetal Alchemist: Brotherhood',
   'vote_average': 8.717,
   'vote_count': 2546},
  {'adult': False,
   'backdrop_path': '/rfxryDIv8huejujg4JueDJx8zCz.jpg',
   'genre_ids': [80, 18],
   'id': 60059,
   'origin_country': ['US'],
   'original_language': 'en',
   'original_name': 'Better Call Saul',
   'overview': 'Six years before Saul Goodman meets Walter White. We meet him when the man who will become Saul Goodman is known as Jimmy McGill, a small-time lawyer searching for his destiny, and, more immediately, hustling to make ends meet. Working alongside, and, often, against Jimmy, is “fixer” Mike Ehrmantraut. The series tracks Jimmy’s transformation into Saul Goodman, the man who puts “criminal” in “criminal lawyer".',
   'popularity': 73.2255,
   'poster_path': '/zjg4jpK1Wp2kiRvtt5ND0kznako.jpg',
   'first_air_date': '2015-02-08',
   'softcore': False,
   'name': 'Better Call Saul',
   'vote_average': 8.712,
   'vote_count': 6768},
  {'adult': False,
   'backdrop_path': '/q5mJ4oKfGc6Cr9reIHFzD0pQzre.jpg',
   'genre_ids': [10759, 18],
   'id': 200709,
   'origin_country': ['KR'],
   'original_language': 'ko',
   'original_name': '약한영웅',
   'overview': 'With the aid of unexpected friends, a gifted but introverted student confronts bullies and violent foes — unaware of how dangerous his world will become.',
   'popularity': 49.7635,
   'poster_path': '/5Sd01WeraL2oA3Vv6O4rcRxockn.jpg',
   'first_air_date': '2022-11-18',
   'softcore': False,
   'name': 'Weak Hero',
   'vote_average': 8.698,
   'vote_count': 504}],
 'total_pages': 127,
 'total_results': 2522}

In [8]:
# only results wale section ka json data print krega

response.json()['results']

[{'adult': False,
  'backdrop_path': '/vyG93jhmPL7tBIhRtCLa5mdBKob.jpg',
  'genre_ids': [10759, 18, 35],
  'id': 276161,
  'origin_country': ['KR'],
  'original_language': 'ko',
  'original_name': '참교육',
  'overview': 'An inspector from the Educational Rights Protection Bureau (ERPB) who is authorized by the government to use physical intervention and unconventional methods to discipline delinquent students and reform the educational system.',
  'popularity': 67.8504,
  'poster_path': '/fMECSPrTmRClSViMsXFYmiYIcWP.jpg',
  'first_air_date': '2026-06-05',
  'softcore': False,
  'name': 'Teach You a Lesson',
  'vote_average': 9.42,
  'vote_count': 809},
 {'adult': False,
  'backdrop_path': '/wh5agdl3b7fqC7mSjsCkHx4fMAs.jpg',
  'genre_ids': [37, 18],
  'id': 299167,
  'origin_country': ['US'],
  'original_language': 'en',
  'original_name': 'Dutton Ranch',
  'overview': 'Rip Wheeler and Beth Dutton gamble everything on a new life in South Texas, but the promise of building a future far from the ghosts of Yellowstone quickly collides with brutal new realities and a rival ranch that will stop at nothing to protect its empire.',
  'popularity': 75.4352,
  'poster_path': '/xsiecCxd8lkcAluw0wWwbW5CwSv.jpg',
  'first_air_date': '2026-05-15',
  'softcore': False,
  'name': 'Dutton Ranch',
  'vote_average': 9.166,
  'vote_count': 540},
 {'adult': False,
  'backdrop_path': '/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg',
  'genre_ids': [18, 80],
  'id': 1396,
  'origin_country': ['US'],
  'original_language': 'en',
  'original_name': 'Breaking Bad',
  'overview': "Walter White, a New Mexico chemistry teacher, is diagnosed with Stage III cancer and given a prognosis of only two years left to live. He becomes filled with a sense of fearlessness and an unrelenting desire to secure his family's financial future at any cost as he enters the dangerous world of drugs and crime.",
  'popularity': 148.9727,
  'poster_path': '/anFx9aTOOYqgS3v7x3R84Kz67ly.jpg',
  'first_air_date': '2008-01-20',
  'softcore': False,
  'name': 'Breaking Bad',
  'vote_average': 8.949,
  'vote_count': 18419},
 {'adult': False,
  'backdrop_path': '/3ANXZWhhcqPAh0q6nRZ979TIwxC.jpg',
  'genre_ids': [18],
  'id': 273240,
  'origin_country': ['US'],
  'original_language': 'en',
  'original_name': 'Off Campus',
  'overview': 'Hannah Wells tutors hockey captain Garrett Graham to win over her crush. Their deal becomes real connection as they face their pasts. Friends Logan, Dean, Tucker, and Allie navigate college life and love.',
  'popularity': 77.7385,
  'poster_path': '/tcPc5ZMBO4y2BtCJMe3o2nwZb2B.jpg',
  'first_air_date': '2026-05-13',
  'softcore': False,
  'name': 'Off Campus',
  'vote_average': 8.902,
  'vote_count': 791},
 {'adult': False,
  'backdrop_path': '/810mXC0xkxXVtoKIPGGVgO9PuLh.jpg',
  'genre_ids': [10759, 35, 10765, 18],
  'id': 259837,
  'origin_country': ['KR'],
  'original_language': 'ko',
  'original_name': '원더풀스',
  'overview': 'A goofy group of townies stumbles into superpowers and fights rising evil as doomsday panic grows in this wild, turn-of-the-century action comedy.',
  'popularity': 22.8965,
  'poster_path': '/jj7AYkz2OLRDL1wfJmjTXyWQ5I4.jpg',
  'first_air_date': '2026-05-15',
  'softcore': False,
  'name': 'The WONDERfools',
  'vote_average': 8.9,
  'vote_count': 245},
 {'adult': False,
  'backdrop_path': '/TxicZcsiP9VHYXMYHm4IEHnwv9.jpg',
  'genre_ids': [35, 10765, 10751],
  'id': 245026,
  'origin_country': ['US'],
  'original_language': 'en',
  'original_name': 'Wizards Beyond Waverly Place',
  'overview': "Justin Russo has chosen to lead a normal, mortal life with his family, Giada, Roman and Milo. But when Justin's sister Alex brings Billie to his home seeking help, Justin realizes he must dust off his magical skills to mentor the wizard-in-training while also juggling his everyday responsibilities — and safeguarding the future of the Wizard World.",
  'popularity': 34.1248,
  'poster_path': '/5hrBpjFzIqmN9k7QxEC610gwZGw.jpg',
  'first_air_date': '2024-10-29',
  'softcore': False,
  'name': 'Wizards Beyond Waverly Place',
  'vote_average': 8.9,
  'vote_count': 201},
 {'adult': False,
  'backdrop_path': '/rBOnrVlck7BIlGeWVlzYiZeg4l2.jpg',
  'genre_ids': [16, 10759, 18, 10765],
  'id': 209867,
  'origin_country': ['JP'],
  'original_language': 'ja',
  'original_name': '葬送のフリーレン',
  'overview': 'After the party of heroes defeated the Demon King, they restored peace to the land and returned to lives of solitude.  Generations pass, and the elven mage Frieren comes face to face with humanity’s mortality. She takes on a new apprentice and promises to fulfill old friends’ dying wishes. Can an elven mind make peace with the nature of life and death? Frieren embarks on her quest to find out.',
  'popularity': 86.0829,
  'poster_path': '/dqZENchTd7lp5zht7BdlqM7RBhD.jpg',
  'first_air_date': '2023-09-29',
  'softcore': False,
  'name': "Frieren: Beyond Journey's End",
  'vote_average': 8.802,
  'vote_count': 932},
 {'adult': False,
  'backdrop_path': '/3siv3RaQrdr2tQiv9jHq71sLlzo.jpg',
  'genre_ids': [10759, 10751, 18],
  'id': 85077,
  'origin_country': ['US'],
  'original_language': 'en',
  'original_name': 'The Chosen',
  'overview': 'The life of Christ through the eyes of those who encountered him.',
  'popularity': 62.3312,
  'poster_path': '/dqVUFuNrMFWt7uGNWlpo91VKYOI.jpg',
  'first_air_date': '2019-04-21',
  'softcore': False,
  'name': 'The Chosen',
  'vote_average': 8.794,
  'vote_count': 952},
 {'adult': False,
  'backdrop_path': '/7oBGhqJIghRBvOwo5Qe0yM0cnMc.jpg',
  'genre_ids': [16, 10759, 10765],
  'id': 246,
  'origin_country': ['US'],
  'original_language': 'en',
  'original_name': 'Avatar: The Last Airbender',
  'overview': 'In a war-torn world of elemental magic, a young boy reawakens to undertake a dangerous mystic quest to fulfill his destiny as the Avatar, and bring peace to the world.',
  'popularity': 30.8563,
  'poster_path': '/yaGt4GIutpbXHsv48tWceWg6s56.jpg',
  'first_air_date': '2005-02-21',
  'softcore': False,
  'name': 'Avatar: The Last Airbender',
  'vote_average': 8.778,
  'vote_count': 5051},
 {'adult': False,
  'backdrop_path': '/a9qlroMOHewiDsUR93PYMVfpbF5.jpg',
  'genre_ids': [18],
  'id': 219246,
  'origin_country': ['KR'],
  'original_language': 'ko',
  'original_name': '폭싹 속았수다',
  'overview': "In Jeju, a spirited girl and a steadfast boy's island story blossoms into a lifelong tale of setbacks and triumphs — proving love endures across time.",
  'popularity': 25.7212,
  'poster_path': '/1VC3sEFxYXYDqQUCAnvWfUsYg1s.jpg',
  'first_air_date': '2025-03-07',
  'softcore': False,
  'name': 'When Life Gives You Tangerines',
  'vote_average': 8.763,
  'vote_count': 570},
 {'adult': False,
  'backdrop_path': '/wgmikRStgBbrzjxFVe5rhFlpL2R.jpg',
  'genre_ids': [35],
  'id': 64010,
  'origin_country': ['KR'],
  'original_language': 'ko',
  'original_name': '응답하라 1988',
  'overview': 'Take a nostalgic trip back to the late 1980s through the lives of five families and their five teenage kids living in a small neighbourhood in Seoul.',
  'popularity': 16.305,
  'poster_path': '/i3xQJlQRff4k5IMEY55l4iKaKl3.jpg',
  'first_air_date': '2015-11-06',
  'softcore': False,
  'name': 'Reply 1988',
  'vote_average': 8.759,
  'vote_count': 222},
 {'adult': False,
  'backdrop_path': '/q8eejQcg1bAqImEV8jh8RtBD4uH.jpg',
  'genre_ids': [16, 10759, 10765],
  'id': 94605,
  'origin_country': ['US'],
  'original_language': 'en',
  'original_name': 'Arcane',
  'overview': 'Amid the stark discord of twin cities Piltover and Zaun, two sisters fight on rival sides of a war between magic technologies and clashing convictions.',
  'popularity': 35.1375,
  'poster_path': '/fqldf2t8ztc9aiwn3k6mlX3tvRT.jpg',
  'first_air_date': '2021-11-06',
  'softcore': False,
  'name': 'Arcane',
  'vote_average': 8.8,
  'vote_count': 6106},
 {'adult': False,
  'backdrop_path': '/2rmK7mnchw9Xr3XdiTFSxTTLXqv.jpg',
  'genre_ids': [10759, 35, 16],
  'id': 37854,
  'origin_country': ['JP'],
  'original_language': 'ja',
  'original_name': 'ワンピース',
  'overview': 'Years ago, the fearsome Pirate King, Gol D. Roger was executed leaving a huge pile of treasure and the famous "One Piece" behind. Whoever claims the "One Piece" will be named the new King of the Pirates.\n\nMonkey D. Luffy, a boy who consumed a "Devil Fruit," decides to follow in the footsteps of his idol, the pirate Shanks, and find the One Piece. It helps, of course, that his body has the properties of rubber and that he\'s surrounded by a bevy of skilled fighters and thieves to help him along the way.\n\nLuffy will do anything to get the One Piece and become King of the Pirates!',
  'popularity': 49.6344,
  'poster_path': '/dB4EDhre2dsC2kxYDavyKWqLQwi.jpg',
  'first_air_date': '1999-10-20',
  'softcore': False,
  'name': 'One Piece',
  'vote_average': 8.75,
  'vote_count': 5487},
 {'adult': False,
  'backdrop_path': '/iS76c29IrS3lKI2X5CFySguiAWU.jpg',
  'genre_ids': [18],
  'id': 301507,
  'origin_country': ['CA'],
  'original_language': 'en',
  'original_name': 'Heated Rivalry',
  'overview': 'Two of the biggest stars in Major League Hockey are bound by ambition, rivalry, and a magnetic pull neither of them fully understands. What begins as a secret fling between two fresh faced rookies evolves into a years-long journey of love, denial, and self-discovery. Over the next eight years, as they chase glory on the ice, they struggle to navigate their feelings for each other. Torn between the sport they live for and the love they can’t ignore, they must decide if there’s room in their fiercely competitive world for something as fragile – and powerful – as real love.',
  'popularity': 33.8137,
  'poster_path': '/3YCKbtAkYWCMDLHvkUjGhG7eWoS.jpg',
  'first_air_date': '2025-11-28',
  'softcore': False,
  'name': 'Heated Rivalry',
  'vote_average': 8.738,
  'vote_count': 582},
 {'adult': False,
  'backdrop_path': '/jmV6NIzZxGzRoljFPwao6sh4Nny.jpg',
  'genre_ids': [18, 35],
  'id': 259666,
  'origin_country': ['MX'],
  'original_language': 'es',
  'original_name': 'Nadie nos va a extrañar',
  'overview': "It's the '90s, and five losers run an illegal business at their high school. They sell homework and assignments to their classmates. The advantage is that no one ever suspects the nerds. Their business brings them money and popularity. But hormones and an unexpected death threaten to ruin everything. If the business collapses, their futures and their friendships are at risk.",
  'popularity': 42.0105,
  'poster_path': '/5U3WiAz67fJn5gnvFk4zOJAx9Sc.jpg',
  'first_air_date': '2024-08-09',
  'softcore': False,
  'name': 'No One Will Miss Us',
  'vote_average': 8.7,
  'vote_count': 351},
 {'adult': False,
  'backdrop_path': '/z3BkMbCy5ajZPMyKEUwsPHuz2cV.jpg',
  'genre_ids': [18],
  'id': 250307,
  'origin_country': ['US'],
  'original_language': 'en',
  'original_name': 'The Pitt',
  'overview': "The staff of Pittsburgh's Trauma Medical Center work around the clock to save lives in an overcrowded and underfunded emergency department.",
  'popularity': 85.638,
  'poster_path': '/kvFSpESyBZMjaeOJDx7RS3P1jey.jpg',
  'first_air_date': '2025-01-09',
  'softcore': False,
  'name': 'The Pitt',
  'vote_average': 8.722,
  'vote_count': 910},
 {'adult': False,
  'backdrop_path': '/3URK0z9PzpVNJrGE7XOuyy6KFzk.jpg',
  'genre_ids': [18],
  'id': 87108,
  'origin_country': ['US'],
  'original_language': 'en',
  'original_name': 'Chernobyl',
  'overview': 'The true story of one of the worst man-made catastrophes in history: the catastrophic nuclear accident at Chernobyl. A tale of the brave men and women who sacrificed to save Europe from unimaginable disaster.',
  'popularity': 40.9514,
  'poster_path': '/hlLXt2tOPT6RRnjiUmoxyG1LTFi.jpg',
  'first_air_date': '2019-05-06',
  'softcore': False,
  'name': 'Chernobyl',
  'vote_average': 8.722,
  'vote_count': 8179},
 {'adult': False,
  'backdrop_path': '/2UG177tWHy7xRmMKWJHB7nAUmKd.jpg',
  'genre_ids': [16, 10759, 10765, 18],
  'id': 31911,
  'origin_country': ['JP'],
  'original_language': 'ja',
  'original_name': '鋼の錬金術師 FULLMETAL ALCHEMIST',
  'overview': 'Disregard for alchemy’s laws ripped half of Edward Elric’s limbs from his body and left his brother Alphonse’s soul clinging to a suit of armor. To restore what was lost, the brothers seek the Philosopher’s Stone. Enemies and allies – the corrupt military, the Homunculi, and foreign alchemists – will alter the Elric brothers course, but their purpose will remain unchanged and their bond unbreakable.',
  'popularity': 47.2786,
  'poster_path': '/5ZFUEOULaVml7pQuXxhpR2SmVUw.jpg',
  'first_air_date': '2009-04-05',
  'softcore': False,
  'name': 'Fullmetal Alchemist: Brotherhood',
  'vote_average': 8.717,
  'vote_count': 2546},
 {'adult': False,
  'backdrop_path': '/rfxryDIv8huejujg4JueDJx8zCz.jpg',
  'genre_ids': [80, 18],
  'id': 60059,
  'origin_country': ['US'],
  'original_language': 'en',
  'original_name': 'Better Call Saul',
  'overview': 'Six years before Saul Goodman meets Walter White. We meet him when the man who will become Saul Goodman is known as Jimmy McGill, a small-time lawyer searching for his destiny, and, more immediately, hustling to make ends meet. Working alongside, and, often, against Jimmy, is “fixer” Mike Ehrmantraut. The series tracks Jimmy’s transformation into Saul Goodman, the man who puts “criminal” in “criminal lawyer".',
  'popularity': 73.2255,
  'poster_path': '/zjg4jpK1Wp2kiRvtt5ND0kznako.jpg',
  'first_air_date': '2015-02-08',
  'softcore': False,
  'name': 'Better Call Saul',
  'vote_average': 8.712,
  'vote_count': 6768},
 {'adult': False,
  'backdrop_path': '/q5mJ4oKfGc6Cr9reIHFzD0pQzre.jpg',
  'genre_ids': [10759, 18],
  'id': 200709,
  'origin_country': ['KR'],
  'original_language': 'ko',
  'original_name': '약한영웅',
  'overview': 'With the aid of unexpected friends, a gifted but introverted student confronts bullies and violent foes — unaware of how dangerous his world will become.',
  'popularity': 49.7635,
  'poster_path': '/5Sd01WeraL2oA3Vv6O4rcRxockn.jpg',
  'first_air_date': '2022-11-18',
  'softcore': False,
  'name': 'Weak Hero',
  'vote_average': 8.698,
  'vote_count': 504}]

In [ ]:
# Creating the dataframe :

In [9]:
pd.DataFrame(response.json()['results'])

,adult,backdrop_path,genre_ids,id,origin_country,original_language,original_name,overview,popularity,poster_path,first_air_date,softcore,name,vote_average,vote_count
0,False,/vyG93jhmPL7tBIhRtCLa5mdBKob.jpg,"[10759, 18, 35]",276161,[KR],ko,참교육,An inspector from the Educational Rights Prote...,67.8504,/fMECSPrTmRClSViMsXFYmiYIcWP.jpg,2026-06-05,False,Teach You a Lesson,9.420,809
1,False,/wh5agdl3b7fqC7mSjsCkHx4fMAs.jpg,"[37, 18]",299167,[US],en,Dutton Ranch,Rip Wheeler and Beth Dutton gamble everything ...,75.4352,/xsiecCxd8lkcAluw0wWwbW5CwSv.jpg,2026-05-15,False,Dutton Ranch,9.166,540
2,False,/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg,"[18, 80]",1396,[US],en,Breaking Bad,"Walter White, a New Mexico chemistry teacher, ...",148.9727,/anFx9aTOOYqgS3v7x3R84Kz67ly.jpg,2008-01-20,False,Breaking Bad,8.949,18419
3,False,/3ANXZWhhcqPAh0q6nRZ979TIwxC.jpg,[18],273240,[US],en,Off Campus,Hannah Wells tutors hockey captain Garrett Gra...,77.7385,/tcPc5ZMBO4y2BtCJMe3o2nwZb2B.jpg,2026-05-13,False,Off Campus,8.902,791
4,False,/810mXC0xkxXVtoKIPGGVgO9PuLh.jpg,"[10759, 35, 10765, 18]",259837,[KR],ko,원더풀스,A goofy group of townies stumbles into superpo...,22.8965,/jj7AYkz2OLRDL1wfJmjTXyWQ5I4.jpg,2026-05-15,False,The WONDERfools,8.900,245
5,False,/TxicZcsiP9VHYXMYHm4IEHnwv9.jpg,"[35, 10765, 10751]",245026,[US],en,Wizards Beyond Waverly Place,"Justin Russo has chosen to lead a normal, mort...",34.1248,/5hrBpjFzIqmN9k7QxEC610gwZGw.jpg,2024-10-29,False,Wizards Beyond Waverly Place,8.900,201
6,False,/rBOnrVlck7BIlGeWVlzYiZeg4l2.jpg,"[16, 10759, 18, 10765]",209867,[JP],ja,葬送のフリーレン,After the party of heroes defeated the Demon K...,86.0829,/dqZENchTd7lp5zht7BdlqM7RBhD.jpg,2023-09-29,False,Frieren: Beyond Journey's End,8.802,932
7,False,/3siv3RaQrdr2tQiv9jHq71sLlzo.jpg,"[10759, 10751, 18]",85077,[US],en,The Chosen,The life of Christ through the eyes of those w...,62.3312,/dqVUFuNrMFWt7uGNWlpo91VKYOI.jpg,2019-04-21,False,The Chosen,8.794,952
8,False,/7oBGhqJIghRBvOwo5Qe0yM0cnMc.jpg,"[16, 10759, 10765]",246,[US],en,Avatar: The Last Airbender,"In a war-torn world of elemental magic, a youn...",30.8563,/yaGt4GIutpbXHsv48tWceWg6s56.jpg,2005-02-21,False,Avatar: The Last Airbender,8.778,5051
9,False,/a9qlroMOHewiDsUR93PYMVfpbF5.jpg,[18],219246,[KR],ko,폭싹 속았수다,"In Jeju, a spirited girl and a steadfast boy's...",25.7212,/1VC3sEFxYXYDqQUCAnvWfUsYg1s.jpg,2025-03-07,False,When Life Gives You Tangerines,8.763,570
10,False,/wgmikRStgBbrzjxFVe5rhFlpL2R.jpg,[35],64010,[KR],ko,응답하라 1988,Take a nostalgic trip back to the late 1980s t...,16.3050,/i3xQJlQRff4k5IMEY55l4iKaKl3.jpg,2015-11-06,False,Reply 1988,8.759,222
11,False,/q8eejQcg1bAqImEV8jh8RtBD4uH.jpg,"[16, 10759, 10765]",94605,[US],en,Arcane,Amid the stark discord of twin cities Piltover...,35.1375,/fqldf2t8ztc9aiwn3k6mlX3tvRT.jpg,2021-11-06,False,Arcane,8.800,6106
12,False,/2rmK7mnchw9Xr3XdiTFSxTTLXqv.jpg,"[10759, 35, 16]",37854,[JP],ja,ワンピース,"Years ago, the fearsome Pirate King, Gol D. Ro...",49.6344,/dB4EDhre2dsC2kxYDavyKWqLQwi.jpg,1999-10-20,False,One Piece,8.750,5487
13,False,/iS76c29IrS3lKI2X5CFySguiAWU.jpg,[18],301507,[CA],en,Heated Rivalry,Two of the biggest stars in Major League Hocke...,33.8137,/3YCKbtAkYWCMDLHvkUjGhG7eWoS.jpg,2025-11-28,False,Heated Rivalry,8.738,582
14,False,/jmV6NIzZxGzRoljFPwao6sh4Nny.jpg,"[18, 35]",259666,[MX],es,Nadie nos va a extrañar,"It's the '90s, and five losers run an illegal ...",42.0105,/5U3WiAz67fJn5gnvFk4zOJAx9Sc.jpg,2024-08-09,False,No One Will Miss Us,8.700,351
15,False,/z3BkMbCy5ajZPMyKEUwsPHuz2cV.jpg,[18],250307,[US],en,The Pitt,The staff of Pittsburgh's Trauma Medical Cente...,85.6380,/kvFSpESyBZMjaeOJDx7RS3P1jey.jpg,2025-01-09,False,The Pitt,8.722,910
16,False,/3URK0z9PzpVNJrGE7XOuyy6KFzk.jpg,[18],87108,[US],en,Chernobyl,The true story of one of the worst man-made ca...,40.9514,/hlLXt2tOPT6RRnjiUmoxyG1LTFi.jpg,2019-05-06,False,Chernobyl,8.722,8179
17,False,/2UG177tWHy7xRmMKWJHB7nAUmKd.jpg,"[16, 10759, 10765, 18]",31911,[JP],ja,鋼の錬金術師 FULLMETAL ALCHEMIST,Disregard for alchemy’s laws ripped half of Ed...,47.2786,/5ZFUEOULaVml7pQuXxhpR2SmVUw.jpg,2009-04-05,False,Fullmetal Alchemist: Brotherhood,8.717,2546
18,False,/rfxryDIv8huejujg4JueDJx8zCz.jpg,"[80, 18]",60059,[US],en,Better Call Saul,Six years before Saul Goodman meets Walter Whi...,73.2255,/zjg4jpK1Wp2kiRvtt5ND0kznako.jpg,2015-02-08,False,Better Call Saul,8.712,6768
19,False,/q5mJ4oKfGc6Cr9reIHFzD0pQzre.jpg,"[10759, 18]",200709,[KR],ko,약한영웅,"With the aid of unexpected friends, a gifted b...",49.7635,/5Sd01WeraL2oA3Vv6O4rcRxockn.jpg,2022-11-18,False,Weak Hero,8.698,504

In [10]:
pd.DataFrame(response.json()['results']).head(2)

,adult,backdrop_path,genre_ids,id,origin_country,original_language,original_name,overview,popularity,poster_path,first_air_date,softcore,name,vote_average,vote_count
0,False,/vyG93jhmPL7tBIhRtCLa5mdBKob.jpg,"[10759, 18, 35]",276161,[KR],ko,참교육,An inspector from the Educational Rights Prote...,67.8504,/fMECSPrTmRClSViMsXFYmiYIcWP.jpg,2026-06-05,False,Teach You a Lesson,9.420,809
1,False,/wh5agdl3b7fqC7mSjsCkHx4fMAs.jpg,"[37, 18]",299167,[US],en,Dutton Ranch,Rip Wheeler and Beth Dutton gamble everything ...,75.4352,/xsiecCxd8lkcAluw0wWwbW5CwSv.jpg,2026-05-15,False,Dutton Ranch,9.166,540

In [ ]:
# Storing the required column data into the dataframe

In [12]:
pd.DataFrame(response.json()['results'])[['id' , 'name' , 'overview' , 'first_air_date' , 'popularity' , 'vote_average' , 'vote_count']]

,id,name,overview,first_air_date,popularity,vote_average,vote_count
0,276161,Teach You a Lesson,An inspector from the Educational Rights Prote...,2026-06-05,67.8504,9.420,809
1,299167,Dutton Ranch,Rip Wheeler and Beth Dutton gamble everything ...,2026-05-15,75.4352,9.166,540
2,1396,Breaking Bad,"Walter White, a New Mexico chemistry teacher, ...",2008-01-20,148.9727,8.949,18419
3,273240,Off Campus,Hannah Wells tutors hockey captain Garrett Gra...,2026-05-13,77.7385,8.902,791
4,259837,The WONDERfools,A goofy group of townies stumbles into superpo...,2026-05-15,22.8965,8.900,245
5,245026,Wizards Beyond Waverly Place,"Justin Russo has chosen to lead a normal, mort...",2024-10-29,34.1248,8.900,201
6,209867,Frieren: Beyond Journey's End,After the party of heroes defeated the Demon K...,2023-09-29,86.0829,8.802,932
7,85077,The Chosen,The life of Christ through the eyes of those w...,2019-04-21,62.3312,8.794,952
8,246,Avatar: The Last Airbender,"In a war-torn world of elemental magic, a youn...",2005-02-21,30.8563,8.778,5051
9,219246,When Life Gives You Tangerines,"In Jeju, a spirited girl and a steadfast boy's...",2025-03-07,25.7212,8.763,570
10,64010,Reply 1988,Take a nostalgic trip back to the late 1980s t...,2015-11-06,16.3050,8.759,222
11,94605,Arcane,Amid the stark discord of twin cities Piltover...,2021-11-06,35.1375,8.800,6106
12,37854,One Piece,"Years ago, the fearsome Pirate King, Gol D. Ro...",1999-10-20,49.6344,8.750,5487
13,301507,Heated Rivalry,Two of the biggest stars in Major League Hocke...,2025-11-28,33.8137,8.738,582
14,259666,No One Will Miss Us,"It's the '90s, and five losers run an illegal ...",2024-08-09,42.0105,8.700,351
15,250307,The Pitt,The staff of Pittsburgh's Trauma Medical Cente...,2025-01-09,85.6380,8.722,910
16,87108,Chernobyl,The true story of one of the worst man-made ca...,2019-05-06,40.9514,8.722,8179
17,31911,Fullmetal Alchemist: Brotherhood,Disregard for alchemy’s laws ripped half of Ed...,2009-04-05,47.2786,8.717,2546
18,60059,Better Call Saul,Six years before Saul Goodman meets Walter Whi...,2015-02-08,73.2255,8.712,6768
19,200709,Weak Hero,"With the aid of unexpected friends, a gifted b...",2022-11-18,49.7635,8.698,504

In [13]:
df = pd.DataFrame(response.json()['results'])[['id' , 'name' , 'overview' , 'first_air_date' , 'popularity' , 'vote_average' , 'vote_count']]
df.head(5)

,id,name,overview,first_air_date,popularity,vote_average,vote_count
0,276161,Teach You a Lesson,An inspector from the Educational Rights Prote...,2026-06-05,67.8504,9.420,809
1,299167,Dutton Ranch,Rip Wheeler and Beth Dutton gamble everything ...,2026-05-15,75.4352,9.166,540
2,1396,Breaking Bad,"Walter White, a New Mexico chemistry teacher, ...",2008-01-20,148.9727,8.949,18419
3,273240,Off Campus,Hannah Wells tutors hockey captain Garrett Gra...,2026-05-13,77.7385,8.902,791
4,259837,The WONDERfools,A goofy group of townies stumbles into superpo...,2026-05-15,22.8965,8.900,245

In [14]:
df = pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [ ]:
# 127 pages ke data ko dataframe mai add krne ke liye loop chalaya hai or har bar data ko temp_df variable mai store krke usse actual

In [23]:
for i in range(1,128):
    response = requests.get(f'https://api.themoviedb.org/3/tv/top_rated?api_key=2907a3004f657179e96619acd03cc0f8&page={i}')
    temp_df =  pd.DataFrame(response.json()['results'])[['id' , 'name' , 'overview' , 'first_air_date' , 'popularity' , 'vote_average' , 'vote_count']]                       
    df = pd.concat([df, temp_df], ignore_index=True)

In [24]:
df

,id,name,overview,first_air_date,popularity,vote_average,vote_count
0,276161,Teach You a Lesson,An inspector from the Educational Rights Prote...,2026-06-05,67.8419,9.420,809
1,299167,Dutton Ranch,Rip Wheeler and Beth Dutton gamble everything ...,2026-05-15,72.6345,9.160,541
2,1396,Breaking Bad,"Walter White, a New Mexico chemistry teacher, ...",2008-01-20,147.4670,8.949,18421
3,273240,Off Campus,Hannah Wells tutors hockey captain Garrett Gra...,2026-05-13,77.2183,8.903,792
4,259837,The WONDERfools,A goofy group of townies stumbles into superpo...,2026-05-15,21.7021,8.900,245
...,...,...,...,...,...,...,...
4897,130392,The D'Amelio Show,From relative obscurity and a seemingly normal...,2021-09-03,3.5223,5.009,686
4898,10160,Big Brother,American version of the reality game show whic...,2000-07-05,66.9159,4.846,272
4899,1871,EastEnders,The everyday lives of working-class residents ...,1985-02-19,62.6427,4.249,229
4900,126725,Velma,Jinkies! This raucous reimagining of the Scoob...,2023-01-12,11.5453,3.461,360
4901,224387,Queen Cleopatra,"As Egypt's last pharaoh, Cleopatra fights to p...",2023-05-10,4.3158,2.673,202

In [26]:
df.shape

(4902, 7)

In [27]:
df.to_csv('movies.csv')