## Pandas Export : 
# 1. to csv 
# 2. to excel 
# 3. to html 
# 4. to json 
# 5. to sql

In [9]:
import pandas as pd
df = pd.DataFrame()

# 1. to_csv :

In [20]:
df = pd.read_csv(r"C:\Users\ANUBHAV\Data_Analytics\DAP\Data_Gathering\Datasets\deliveries.csv")
df.head() # --> starting ki 5 rows ko print kreaga.

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN

In [21]:
df.groupby('batsman')['batsman_runs'].sum()  #--> data ko batsman and batsman ke runs ke according club krega.

batsman
A Ashish Reddy     280
A Chandila           4
A Chopra            53
A Choudhary         25
A Dananjaya          4
                  ...
YV Takawale        192
Yashpal Singh       47
Younis Khan          3
Yuvraj Singh      2765
Z Khan             117
Name: batsman_runs, Length: 516, dtype: int64

In [22]:
temp_df = df.groupby('batsman')['batsman_runs'].sum().reset_index() #--> uss data ko temp_df mai store krega

In [8]:
temp_df

            batsman  batsman_runs
0    A Ashish Reddy           280
1        A Chandila             4
2          A Chopra            53
3       A Choudhary            25
4       A Dananjaya             4
..              ...           ...
511     YV Takawale           192
512   Yashpal Singh            47
513     Younis Khan             3
514    Yuvraj Singh          2765
515          Z Khan           117

[516 rows x 2 columns]

In [23]:
temp_df.to_csv('batsman_runs.csv')  #--> temp mai jo created data hai usse as a csv file store krr dega current directory mai.

In [24]:
# creating pivot table : 


df.pivot_table(index = 'batsman' , columns = 'bowling_team' , aggfunc = 'sum' )

                              ball                                 \
bowling_team   Chennai Super Kings Deccan Chargers Delhi Capitals
batsman
A Ashish Reddy                86.0             NaN            NaN
A Chandila                     NaN             6.0            NaN
A Chopra                       NaN           164.0            NaN
A Choudhary                    NaN             NaN            NaN
A Dananjaya                    NaN             NaN            NaN
...                            ...             ...            ...
YV Takawale                   59.0            33.0            NaN
Yashpal Singh                  NaN             NaN            NaN
Younis Khan                    NaN             NaN            NaN
Yuvraj Singh                1082.0           435.0          140.0
Z Khan                       126.0            56.0            NaN

                                                               \
bowling_team   Delhi Daredevils Gujarat Lions Kings XI Punjab
batsman
A Ashish Reddy             94.0           NaN            90.0
A Chandila                  NaN           NaN             NaN
A Chopra                   73.0           NaN            10.0
A Choudhary                 NaN          39.0            25.0
A Dananjaya                22.0           NaN             NaN
...                         ...           ...             ...
YV Takawale                66.0           NaN            31.0
Yashpal Singh              90.0           NaN             NaN
Younis Khan                 NaN           NaN            25.0
Yuvraj Singh             1281.0          94.0           711.0
Z Khan                      6.0           NaN            25.0

                                                                          \
bowling_team   Kochi Tuskers Kerala Kolkata Knight Riders Mumbai Indians
batsman
A Ashish Reddy                  NaN                  59.0           89.0
A Chandila                      NaN                   NaN            NaN
A Chopra                        NaN                   NaN           14.0
A Choudhary                     NaN                   NaN            NaN
A Dananjaya                     NaN                   NaN            NaN
...                             ...                   ...            ...
YV Takawale                     NaN                 247.0            NaN
Yashpal Singh                   NaN                   NaN           22.0
Younis Khan                     NaN                   NaN            NaN
Yuvraj Singh                   53.0                1156.0          990.0
Z Khan                          NaN                 104.0           59.0

                              ...       wide_runs                       \
bowling_team   Pune Warriors  ... Kings XI Punjab Kochi Tuskers Kerala
batsman                       ...
A Ashish Reddy          60.0  ...             0.0                  NaN
A Chandila               NaN  ...             NaN                  NaN
A Chopra                 NaN  ...             0.0                  NaN
A Choudhary              NaN  ...             0.0                  NaN
A Dananjaya              NaN  ...             NaN                  NaN
...                      ...  ...             ...                  ...
YV Takawale              NaN  ...             0.0                  NaN
Yashpal Singh            NaN  ...             NaN                  NaN
Younis Khan              NaN  ...             0.0                  NaN
Yuvraj Singh             NaN  ...             8.0                  1.0
Z Khan                   NaN  ...             0.0                  NaN

                                                                   \
bowling_team   Kolkata Knight Riders Mumbai Indians Pune Warriors
batsman
A Ashish Reddy                   1.0            0.0           0.0
A Chandila                       NaN            NaN           NaN
A Chopra                         NaN            0.0           NaN
A Choudhary                      NaN            NaN           NaN
A Dananjaya                      NaN            NaN           NaN
...                              ...            ...           ...
YV Takawale                      1.0            NaN           NaN
Yashpal Singh                    NaN            0.0           NaN
Younis Khan                      NaN            NaN           NaN
Yuvraj Singh                    16.0            7.0           NaN
Z Khan                           0.0            0.0           NaN

                                                        \
bowling_team   Rajasthan Royals Rising Pune Supergiant
batsman
A Ashish Reddy              0.0                    NaN
A Chandila                  NaN                    NaN
A Chopra                    NaN                    NaN
A Choudhary                 NaN                    NaN
A Dananjaya                 NaN                    NaN
...                         ...                    ...
YV Takawale                 3.0                    NaN
Yashpal Singh               0.0                    NaN
Younis Khan                 NaN                    NaN
Yuvraj Singh               20.0                    1.0
Z Khan                      0.0                    NaN

                                                                    \
bowling_team   Rising Pune Supergiants Royal Challengers Bangalore
batsman
A Ashish Reddy                     NaN                         1.0
A Chandila                         NaN                         0.0
A Chopra                           NaN                         0.0
A Choudhary                        NaN                         NaN
A Dananjaya                        NaN                         NaN
...                                ...                         ...
YV Takawale                        NaN                         NaN
Yashpal Singh                      NaN                         NaN
Younis Khan                        NaN                         NaN
Yuvraj Singh                       0.0                         7.0
Z Khan                             NaN                         0.0


bowling_team   Sunrisers Hyderabad
batsman
A Ashish Reddy                 NaN
A Chandila                     NaN
A Chopra                       NaN
A Choudhary                    0.0
A Dananjaya                    NaN
...                            ...
YV Takawale                    NaN
Yashpal Singh                  NaN
Younis Khan                    NaN
Yuvraj Singh                   0.0
Z Khan                         0.0

[516 rows x 285 columns]

                              ball                                 \
bowling_team   Chennai Super Kings Deccan Chargers Delhi Capitals
batsman
A Ashish Reddy                86.0             NaN            NaN
A Chandila                     NaN             6.0            NaN
A Chopra                       NaN           164.0            NaN
A Choudhary                    NaN             NaN            NaN
A Dananjaya                    NaN             NaN            NaN
...                            ...             ...            ...
YV Takawale                   59.0            33.0            NaN
Yashpal Singh                  NaN             NaN            NaN
Younis Khan                    NaN             NaN            NaN
Yuvraj Singh                1082.0           435.0          140.0
Z Khan                       126.0            56.0            NaN

                                                               \
bowling_team   Delhi Daredevils Gujarat Lions Kings XI Punjab
batsman
A Ashish Reddy             94.0           NaN            90.0
A Chandila                  NaN           NaN             NaN
A Chopra                   73.0           NaN            10.0
A Choudhary                 NaN          39.0            25.0
A Dananjaya                22.0           NaN             NaN
...                         ...           ...             ...
YV Takawale                66.0           NaN            31.0
Yashpal Singh              90.0           NaN             NaN
Younis Khan                 NaN           NaN            25.0
Yuvraj Singh             1281.0          94.0           711.0
Z Khan                      6.0           NaN            25.0

                                                                          \
bowling_team   Kochi Tuskers Kerala Kolkata Knight Riders Mumbai Indians
batsman
A Ashish Reddy                  NaN                  59.0           89.0
A Chandila                      NaN                   NaN            NaN
A Chopra                        NaN                   NaN           14.0
A Choudhary                     NaN                   NaN            NaN
A Dananjaya                     NaN                   NaN            NaN
...                             ...                   ...            ...
YV Takawale                     NaN                 247.0            NaN
Yashpal Singh                   NaN                   NaN           22.0
Younis Khan                     NaN                   NaN            NaN
Yuvraj Singh                   53.0                1156.0          990.0
Z Khan                          NaN                 104.0           59.0

                              ...       wide_runs                       \
bowling_team   Pune Warriors  ... Kings XI Punjab Kochi Tuskers Kerala
batsman                       ...
A Ashish Reddy          60.0  ...             0.0                  NaN
A Chandila               NaN  ...             NaN                  NaN
A Chopra                 NaN  ...             0.0                  NaN
A Choudhary              NaN  ...             0.0                  NaN
A Dananjaya              NaN  ...             NaN                  NaN
...                      ...  ...             ...                  ...
YV Takawale              NaN  ...             0.0                  NaN
Yashpal Singh            NaN  ...             NaN                  NaN
Younis Khan              NaN  ...             0.0                  NaN
Yuvraj Singh             NaN  ...             8.0                  1.0
Z Khan                   NaN  ...             0.0                  NaN

                                                                   \
bowling_team   Kolkata Knight Riders Mumbai Indians Pune Warriors
batsman
A Ashish Reddy                   1.0            0.0           0.0
A Chandila                       NaN            NaN           NaN
A Chopra                         NaN            0.0           NaN
A Choudhary                      NaN            NaN           NaN
A Dananjaya                      NaN            NaN           NaN
...                              ...            ...           ...
YV Takawale                      1.0            NaN           NaN
Yashpal Singh                    NaN            0.0           NaN
Younis Khan                      NaN            NaN           NaN
Yuvraj Singh                    16.0            7.0           NaN
Z Khan                           0.0            0.0           NaN

                                                        \
bowling_team   Rajasthan Royals Rising Pune Supergiant
batsman
A Ashish Reddy              0.0                    NaN
A Chandila                  NaN                    NaN
A Chopra                    NaN                    NaN
A Choudhary                 NaN                    NaN
A Dananjaya                 NaN                    NaN
...                         ...                    ...
YV Takawale                 3.0                    NaN
Yashpal Singh               0.0                    NaN
Younis Khan                 NaN                    NaN
Yuvraj Singh               20.0                    1.0
Z Khan                      0.0                    NaN

                                                                    \
bowling_team   Rising Pune Supergiants Royal Challengers Bangalore
batsman
A Ashish Reddy                     NaN                         1.0
A Chandila                         NaN                         0.0
A Chopra                           NaN                         0.0
A Choudhary                        NaN                         NaN
A Dananjaya                        NaN                         NaN
...                                ...                         ...
YV Takawale                        NaN                         NaN
Yashpal Singh                      NaN                         NaN
Younis Khan                        NaN                         NaN
Yuvraj Singh                       0.0                         7.0
Z Khan                             NaN                         0.0


bowling_team   Sunrisers Hyderabad
batsman
A Ashish Reddy                 NaN
A Chandila                     NaN
A Chopra                       NaN
A Choudhary                    0.0
A Dananjaya                    NaN
...                            ...
YV Takawale                    NaN
Yashpal Singh                  NaN
Younis Khan                    NaN
Yuvraj Singh                   0.0
Z Khan                         0.0

[516 rows x 285 columns]

In [25]:
# storing the pivot_table : 


df.pivot_table(index = 'batsman' , columns = 'bowling_team' , aggfunc = 'sum' ).to_csv('batsman_vs_team.csv' , index = False)

## 2. to_excel :

In [26]:
temp_df = df.groupby('batsman')['batsman_runs'].sum().reset_index()  # --> uss data ko temp_df mai store krega

In [27]:
temp_df

            batsman  batsman_runs
0    A Ashish Reddy           280
1        A Chandila             4
2          A Chopra            53
3       A Choudhary            25
4       A Dananjaya             4
..              ...           ...
511     YV Takawale           192
512   Yashpal Singh            47
513     Younis Khan             3
514    Yuvraj Singh          2765
515          Z Khan           117

[516 rows x 2 columns]

In [13]:
temp_df.to_excel("batsman_runs.xlsx")   #--> temp mai jo created data hai usse as a excel file store krr dega current directory mai.

In [22]:
# storing the data in excel with particular sheet:  

# :--> sheet_1 :
temp_df.to_excel("output_runs.xlsx" , sheet_name = 'batsman_runs' )

In [24]:
# :--> sheet_2 :
temp_df2 = df.pivot_table(index = 'batsman' , columns = 'bowling_team' , aggfunc = 'sum' )

In [25]:
with pd.ExcelWriter('Output.xlsx') as writer:                               #--> ExcelWriter ak excel file mai do alag - alag sheet banata hai           
    temp_df.to_excel(writer , sheet_name = 'sheet_name_1')
    temp_df2.to_excel(writer , sheet_name = 'sheet_name_2')

## 3. to_html : 
#  blog form mai html table mai data mo store krta hai .

In [26]:
df.pivot_table(index = 'over' , columns = 'ball' , values = 'batsman_runs' , aggfunc = 'count')

ball     1     2     3     4     5     6    7   8   9
over
1     1527  1528  1526  1526  1523  1523  372  65  13
2     1511  1509  1509  1509  1509  1510  356  74  11
3     1511  1510  1509  1509  1509  1509  294  54  10
4     1512  1509  1508  1510  1509  1509  274  39   9
5     1509  1508  1507  1507  1507  1508  259  36   4
6     1505  1504  1503  1503  1502  1502  264  37   6
7     1501  1500  1500  1500  1500  1500  239  36   7
8     1500  1500  1499  1499  1499  1498  226  29   3
9     1495  1494  1493  1493  1493  1493  232  34   4
10    1495  1493  1492  1492  1490  1490  208  21   3
11    1486  1485  1485  1484  1484  1484  182  27   3
12    1479  1477  1477  1477  1477  1477  201  19   6
13    1472  1471  1471  1470  1470  1469  215  32   3
14    1466  1462  1460  1457  1455  1451  192  33   2
15    1445  1445  1441  1439  1435  1433  236  23   3
16    1424  1420  1412  1409  1405  1403  245  41   2
17    1399  1392  1388  1381  1378  1372  289  43   6
18    1361  1350  1344  1338  1323  1314  289  59   9
19    1293  1278  1262  1244  1222  1201  297  57  12
20    1156  1128  1092  1065  1030   982  243  36   6

In [27]:
df.query('batsman_runs == 6').pivot_table(index = 'over' , columns = 'ball' , values = 'batsman_runs' , aggfunc = 'count') # ye query pivot table
# mai se kisi bhi over mai , kisi bhi ball pe historically kitne six lagte hai.

ball     1      2      3      4      5      6     7    8    9
over
1      7.0   12.0   27.0   31.0   24.0   20.0  12.0  1.0  NaN
2     26.0   30.0   35.0   43.0   45.0   42.0  10.0  5.0  NaN
3     63.0   46.0   57.0   52.0   48.0   58.0   8.0  2.0  1.0
4     49.0   61.0   51.0   81.0   54.0   53.0  11.0  1.0  NaN
5     54.0   56.0   82.0   64.0   62.0   60.0  10.0  2.0  NaN
6     61.0   82.0   44.0   65.0   56.0   66.0  11.0  1.0  NaN
7     27.0   45.0   34.0   44.0   51.0   28.0   3.0  3.0  NaN
8     44.0   47.0   55.0   49.0   53.0   39.0   7.0  NaN  NaN
9     70.0   56.0   56.0   58.0   52.0   35.0  11.0  NaN  1.0
10    43.0   38.0   60.0   43.0   52.0   54.0   9.0  1.0  NaN
11    59.0   70.0   62.0   54.0   61.0   56.0   8.0  NaN  NaN
12    70.0   58.0   72.0   63.0   65.0   52.0  11.0  1.0  NaN
13    67.0   87.0   58.0   80.0   75.0   65.0  10.0  2.0  NaN
14    83.0   85.0   79.0   74.0   65.0   71.0   7.0  3.0  NaN
15    68.0   93.0   83.0   74.0   64.0   86.0  11.0  1.0  NaN
16    77.0   96.0   95.0   91.0   91.0   78.0  15.0  2.0  NaN
17    84.0   88.0   86.0   87.0  103.0   78.0  20.0  3.0  NaN
18    91.0  111.0  112.0  115.0   94.0  101.0  17.0  1.0  1.0
19    82.0   90.0  114.0  103.0  111.0   98.0  31.0  6.0  3.0
20    99.0   95.0  106.0  113.0   88.0  102.0  24.0  5.0  NaN

In [28]:
df.query('batsman_runs == 6').pivot_table(index = 'over' , columns = 'ball' , values = 'batsman_runs' , aggfunc = 'count').to_html('sixes_heatmap.html')

# 4. to_json :

In [29]:
df

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179073,11415,2,Chennai Super Kings,Mumbai Indians,20,2,RA Jadeja,SR Watson,SL Malinga,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
179074,11415,2,Chennai Super Kings,Mumbai Indians,20,3,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179075,11415,2,Chennai Super Kings,Mumbai Indians,20,4,SR Watson,RA Jadeja,SL Malinga,0,...,0,0,0,0,1,0,1,SR Watson,run out,KH Pandya
179076,11415,2,Chennai Super Kings,Mumbai Indians,20,5,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
179077,11415,2,Chennai Super Kings,Mumbai Indians,20,6,SN Thakur,RA Jadeja,SL Malinga,0,...,0,0,0,0,0,0,0,SN Thakur,lbw,NaN

In [32]:
df.groupby(['batting_team' , 'batsman'])['batsman_runs'].sum().unstack()

batsman,A Ashish Reddy,A Chandila,A Chopra,A Choudhary,A Dananjaya,A Flintoff,A Hales,A Joseph,A Kumble,A Mishra,...,Y Nagar,Y Venugopal Rao,YA Abdulla,YK Pathan,YS Chahal,YV Takawale,Yashpal Singh,Younis Khan,Yuvraj Singh,Z Khan
batting_team,,,,,,,,,,,,,,,,,,,,,
Chennai Super Kings,NaN,NaN,NaN,NaN,NaN,62.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Deccan Chargers,35.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,84.0,...,NaN,446.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Delhi Capitals,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Delhi Daredevils,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,164.0,...,285.0,468.0,NaN,NaN,NaN,NaN,NaN,NaN,248.0,10.0
Gujarat Lions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Kings XI Punjab,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,964.0,NaN
Kochi Tuskers Kerala,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Kolkata Knight Riders,NaN,NaN,53.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1893.0,NaN,NaN,47.0,NaN,NaN,NaN
Mumbai Indians,NaN,NaN,NaN,NaN,4.0,NaN,NaN,15.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,88.0,NaN,NaN,108.0,40.0
Pune Warriors,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,581.0,NaN
Rajasthan Royals,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1029.0,NaN,NaN,NaN,3.0,NaN,NaN
Rising Pune Supergiant,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Rising Pune Supergiants,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Royal Challengers Bangalore,NaN,NaN,NaN,25.0,NaN,NaN,NaN,NaN,35.0,NaN,...,NaN,NaN,NaN,NaN,22.0,104.0,NaN,NaN,376.0,67.0
Sunrisers Hyderabad,245.0,NaN,NaN,NaN,NaN,NaN,152.0,NaN,NaN,93.0,...,NaN,71.0,NaN,319.0,NaN,NaN,NaN,NaN,488.0,NaN

In [33]:
df.groupby(['batting_team' , 'batsman'])['batsman_runs'].sum().unstack().to_json('ipl.json')

# 5. to_sql :

In [11]:
df

Empty DataFrame
Columns: []
Index: []

In [6]:

import pymysql
from sqlalchemy import create_engine

In [10]:
engine = create_engine("mysql+pymysql://root:1020153257@localhost/anubhavdb")
# {root}:{password}@{url}/{database}
df.to_sql('ipl_delivery', con = engine, if_exists = 'append')

0

In [28]:
temp_df.to_sql('batsman_runs', con = engine, if_exists = 'append')  #--> given database "anubhavdb" mai ak new table 'batsman_runs' create krta hai.

516

In [29]:
six_df = df.query('batsman_runs == 6').pivot_table(index='over',columns='ball',values='batsman_runs',aggfunc='count')

In [30]:
six_df.to_sql('six_heatmap', con = engine, if_exists = 'append')

20