                                                                Data Gathering
                                                            [  working-with-csv  ]

In [27]:
import pandas as pd

## 1. Importing the local csv file :

In [28]:
df = pd.read_csv(r"C:\Users\ANUBHAV\Data_Analytics\DAP\Data_Gathering\Datasets\aug_train.csv")
print(df)

       enrollee_id      city  city_development_index gender  \
0             8949  city_103                   0.920   Male
1            29725   city_40                   0.776   Male
2            11561   city_21                   0.624    NaN
3            33241  city_115                   0.789    NaN
4              666  city_162                   0.767   Male
...            ...       ...                     ...    ...
19153         7386  city_173                   0.878   Male
19154        31398  city_103                   0.920   Male
19155        24576  city_103                   0.920   Male
19156         5756   city_65                   0.802   Male
19157        23834   city_67                   0.855    NaN

           relevent_experience enrolled_university education_level  \
0      Has relevent experience       no_enrollment        Graduate
1       No relevent experience       no_enrollment        Graduate
2       No relevent experience    Full time course        Graduate
3       No relevent experience                 NaN        Graduate
4      Has relevent experience       no_enrollment         Masters
...                        ...                 ...             ...
19153   No relevent experience       no_enrollment        Graduate
19154  Has relevent experience       no_enrollment        Graduate
19155  Has relevent experience       no_enrollment        Graduate
19156  Has relevent experience       no_enrollment     High School
19157   No relevent experience       no_enrollment  Primary School

      major_discipline experience company_size    company_type last_new_job  \
0                 STEM        >20          NaN             NaN            1
1                 STEM         15        50-99         Pvt Ltd           >4
2                 STEM          5          NaN             NaN        never
3      Business Degree         <1          NaN         Pvt Ltd        never
4                 STEM        >20        50-99  Funded Startup            4
...                ...        ...          ...             ...          ...
19153       Humanities         14          NaN             NaN            1
19154             STEM         14          NaN             NaN            4
19155             STEM        >20        50-99         Pvt Ltd            4
19156              NaN         <1      500-999         Pvt Ltd            2
19157              NaN          2          NaN             NaN            1

       training_hours  target
0                  36     1.0
1                  47     0.0
2                  83     0.0
3                  52     1.0
4                   8     0.0
...               ...     ...
19153              42     1.0
19154              52     1.0
19155              44     0.0
19156              97     0.0
19157             127     0.0

[19158 rows x 14 columns]

## 2. Opening a csv file from an URL :

In [29]:
import requests
from io import StringIO

url = "https://raw.githubusercontent.com/cs109/2014_data/master/countries.csv"
headers = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0"}
req = requests.get(url, headers=headers)
data = StringIO(req.text)

pd.read_csv(data)

       Country         Region
0      Algeria         AFRICA
1       Angola         AFRICA
2        Benin         AFRICA
3     Botswana         AFRICA
4      Burkina         AFRICA
..         ...            ...
189   Paraguay  SOUTH AMERICA
190       Peru  SOUTH AMERICA
191   Suriname  SOUTH AMERICA
192    Uruguay  SOUTH AMERICA
193  Venezuela  SOUTH AMERICA

[194 rows x 2 columns]

## 3. Sep and name Parameter :

In [30]:
pd.read_csv(r'C:\Users\ANUBHAV\Data_Analytics\DAP\Data_Gathering\Datasets\movie_titles_metadata.tsv')

pd.read_csv(r'C:\Users\ANUBHAV\Data_Analytics\DAP\Data_Gathering\Datasets\movie_titles_metadata.tsv' , sep = '\t')

,m0,10 things i hate about you,1999,6.90,62847,['comedy' 'romance']
0,m1,1492: conquest of paradise,1992,6.2,10421.0,['adventure' 'biography' 'drama' 'history']
1,m2,15 minutes,2001,6.1,25854.0,['action' 'crime' 'drama' 'thriller']
2,m3,2001: a space odyssey,1968,8.4,163227.0,['adventure' 'mystery' 'sci-fi']
3,m4,48 hrs.,1982,6.9,22289.0,['action' 'comedy' 'crime' 'drama' 'thriller']
4,m5,the fifth element,1997,7.5,133756.0,['action' 'adventure' 'romance' 'sci-fi' 'thri...
...,...,...,...,...,...,...
611,m612,watchmen,2009,7.8,135229.0,['action' 'crime' 'fantasy' 'mystery' 'sci-fi'...
612,m613,xxx,2002,5.6,53505.0,['action' 'adventure' 'crime']
613,m614,x-men,2000,7.4,122149.0,['action' 'sci-fi']
614,m615,young frankenstein,1974,8.0,57618.0,['comedy' 'sci-fi']
615,m616,zulu dawn,1979,6.4,1911.0,['action' 'adventure' 'drama' 'history' 'war']

In [31]:
# --> NOTE : 
# names list columns ke name ko contain krti hai  , agar hamare csv data mai headers nahi hai toh ham 
# iss tarah uss file mai header create krr skte hai.

pd.read_csv(r'C:\Users\ANUBHAV\Data_Analytics\DAP\Data_Gathering\Datasets\movie_titles_metadata.tsv' ,sep = '\t' , names = ['sno' , 'name' , 'release_year' , 'rating' , 'votes' , 'genres'])

,sno,name,release_year,rating,votes,genres
0,m0,10 things i hate about you,1999,6.9,62847.0,['comedy' 'romance']
1,m1,1492: conquest of paradise,1992,6.2,10421.0,['adventure' 'biography' 'drama' 'history']
2,m2,15 minutes,2001,6.1,25854.0,['action' 'crime' 'drama' 'thriller']
3,m3,2001: a space odyssey,1968,8.4,163227.0,['adventure' 'mystery' 'sci-fi']
4,m4,48 hrs.,1982,6.9,22289.0,['action' 'comedy' 'crime' 'drama' 'thriller']
...,...,...,...,...,...,...
612,m612,watchmen,2009,7.8,135229.0,['action' 'crime' 'fantasy' 'mystery' 'sci-fi'...
613,m613,xxx,2002,5.6,53505.0,['action' 'adventure' 'crime']
614,m614,x-men,2000,7.4,122149.0,['action' 'sci-fi']
615,m615,young frankenstein,1974,8.0,57618.0,['comedy' 'sci-fi']
616,m616,zulu dawn,1979,6.4,1911.0,['action' 'adventure' 'drama' 'history' 'war']

## 4 Index_col parameter :

In [32]:
# - agar data mai koi aisa column hai jo analysis mai kam nhi ane wala toh ham usse index column mai convert krr skte hai.

In [33]:
# - ex:  
pd.read_csv(r"C:\Users\ANUBHAV\Data_Analytics\DAP\Data_Gathering\Datasets\aug_train.csv" , index_col = "enrollee_id")

,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
enrollee_id,,,,,,,,,,,,,
8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7386,city_173,0.878,Male,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
31398,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
24576,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
5756,city_65,0.802,Male,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

## 5. Header parameter :

In [34]:
# - agar given csv file mai pahle se header present hai but galti se voh as a simple row ki tarah treat ho rha hai toh usse header
#   mai convert krne ke liye header parameter ka use hota hai.

In [35]:
pd.read_csv(r'C:\Users\ANUBHAV\Data_Analytics\DAP\Data_Gathering\Datasets\test.csv')

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,0,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
1,1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0
2,2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0
3,3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1
4,4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0

In [36]:


pd.read_csv(r'C:\Users\ANUBHAV\Data_Analytics\DAP\Data_Gathering\Datasets\test.csv' , header = 1)

,0,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0
1,2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0
2,3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1
3,4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0

## 6. use_cols parameter :

In [37]:
# --> agar hame data import krte vaqt sirf kuch specific cols ko hi import krna hai toh ham use_cols parameter ka use krte hai.

In [38]:

pd.read_csv(r"C:\Users\ANUBHAV\Data_Analytics\DAP\Data_Gathering\Datasets\aug_train.csv" , usecols = ['enrollee_id', 'gender' , 'education_level'])

       enrollee_id gender education_level
0             8949   Male        Graduate
1            29725   Male        Graduate
2            11561    NaN        Graduate
3            33241    NaN        Graduate
4              666   Male         Masters
...            ...    ...             ...
19153         7386   Male        Graduate
19154        31398   Male        Graduate
19155        24576   Male        Graduate
19156         5756   Male     High School
19157        23834    NaN  Primary School

[19158 rows x 3 columns]

## 7. Squeeze parameters :

In [39]:
# --> [ Squeeze = True ] karne se usecols mai given column pandas series ke form mai return krta hai

In [40]:
# df = pd.read_csv(r"C:\Users\ANUBHAV\Data_Analytics\DAP\Data_Gathering\Datasets\aug_train.csv" , usecols = ['gender'] , squeeze = True )
# df


# NOTE :  Squeeze parameter hat chuka hai!

## 8. Skiprows / nrows Parameter :

In [41]:
# --> agar hame kuch specific rows ko skip karana hai data se then ham 'skiprows' ka use krte hai.
# --> agar hame defined amount ke rows ko hi print / load karana haii toh ham 'nrows' ka use krte hai.

In [42]:
pd.read_csv(r"C:\Users\ANUBHAV\Data_Analytics\DAP\Data_Gathering\Datasets\aug_train.csv" ,skiprows = [0 , 4])

pd.read_csv(r"C:\Users\ANUBHAV\Data_Analytics\DAP\Data_Gathering\Datasets\aug_train.csv" ,nrows = 100)

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,Male,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,Male,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,12081,city_65,0.802,Male,Has relevent experience,Full time course,Graduate,STEM,9,50-99,Pvt Ltd,1,33,0.0
96,7364,city_160,0.920,NaN,No relevent experience,Full time course,High School,NaN,2,100-500,Pvt Ltd,1,142,0.0
97,11184,city_74,0.579,NaN,No relevent experience,Full time course,Graduate,STEM,2,100-500,Pvt Ltd,1,34,0.0
98,7016,city_65,0.802,Male,Has relevent experience,no_enrollment,Graduate,STEM,6,50-99,Pvt Ltd,2,14,1.0
99,8695,city_11,0.550,Male,Has relevent experience,no_enrollment,Graduate,STEM,6,10/49,Pvt Ltd,2,27,1.0

## 9.  Encoding parameter :

In [43]:
# --> agar hamare file ka format default(utf-8) nahi hai toh hame ye encoding parameter ko specify krna padta hai, 
# or agar hame actual encoding nahi pata toh phir hame sublime text ka use krke usse convert krna padta utf-8 mai.

In [44]:
pd.read_csv(r'C:\Users\ANUBHAV\Data_Analytics\DAP\Data_Gathering\Datasets\zomato.csv' , encoding = 'latin-1')

,Restaurant ID,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,...,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
0,6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",...,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
1,6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,...,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
2,6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",...,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
3,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",...,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
4,6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",...,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9546,5915730,NamlÛ± Gurme,208,ÛÁstanbul,"Kemankeô Karamustafa Paôa Mahallesi, RÛ±htÛ±...",Karakí_y,"Karakí_y, ÛÁstanbul",28.977392,41.022793,Turkish,...,Turkish Lira(TL),No,No,No,No,3,4.1,Green,Very Good,788
9547,5908749,Ceviz AÛôacÛ±,208,ÛÁstanbul,"Koôuyolu Mahallesi, Muhittin íìstí_ndaÛô Cadd...",Koôuyolu,"Koôuyolu, ÛÁstanbul",29.041297,41.009847,"World Cuisine, Patisserie, Cafe",...,Turkish Lira(TL),No,No,No,No,3,4.2,Green,Very Good,1034
9548,5915807,Huqqa,208,ÛÁstanbul,"Kuruí_eôme Mahallesi, Muallim Naci Caddesi, N...",Kuruí_eôme,"Kuruí_eôme, ÛÁstanbul",29.034640,41.055817,"Italian, World Cuisine",...,Turkish Lira(TL),No,No,No,No,4,3.7,Yellow,Good,661
9549,5916112,Aôôk Kahve,208,ÛÁstanbul,"Kuruí_eôme Mahallesi, Muallim Naci Caddesi, N...",Kuruí_eôme,"Kuruí_eôme, ÛÁstanbul",29.036019,41.057979,Restaurant Cafe,...,Turkish Lira(TL),No,No,No,No,4,4.0,Green,Very Good,901
9550,5927402,Walter's Coffee Roastery,208,ÛÁstanbul,"CafeaÛôa Mahallesi, BademaltÛ± Sokak, No 21/B,...",Moda,"Moda, ÛÁstanbul",29.026016,40.984776,Cafe,...,Turkish Lira(TL),No,No,No,No,2,4.0,Green,Very Good,591

## 10. Skip Bad lines :

In [45]:
# - ye bad rows jo baki rows se jada ya kam data contain krti ho jisse data inconsistent ho skta hai , usse remove krti hai . 
# - Ex :

In [46]:

df = pd.read_csv(
    r'C:\Users\ANUBHAV\Data_Analytics\DAP\Data_Gathering\Datasets\BX-Books.csv',
    sep=';',
    encoding='latin-1',
    on_bad_lines='skip',
    header = 0,
)

df.head()

C:\Users\ANUBHAV\AppData\Local\Temp\ipykernel_28788\2126385218.py:1: DtypeWarning: Columns (0: 2002) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.01.THUMBZZZ.jpg,http://images.amazon.com/images/P/0195153448.01.MZZZZZZZ.jpg,http://images.amazon.com/images/P/0195153448.01.LZZZZZZZ.jpg
0,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
1,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
2,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
3,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...
4,0399135782,The Kitchen God's Wife,Amy Tan,1991,Putnam Pub Group,http://images.amazon.com/images/P/0399135782.0...,http://images.amazon.com/images/P/0399135782.0...,http://images.amazon.com/images/P/0399135782.0...

## 11. dtypes parameters :

In [47]:
# --> ye pandas ki read.csv property( data ko load krne prr column wise uski saare data type ko as it previous define , assign krna ) ko 
#     overwrite krne ke liye use hota hai.

In [48]:
# - Ex: 


# pd.read_csv(r"C:\Users\ANUBHAV\Data_Analytics\DAP\Data_Gathering\Datasets\aug_train.csv").info()  
#--> target columm float hai ,isse column mai convert krna ke liye :

pd.read_csv(r"C:\Users\ANUBHAV\Data_Analytics\DAP\Data_Gathering\Datasets\aug_train.csv" , dtype = {'target' : int} ) 
#--> taget column ko float se int mai convert kiya. 

pd.read_csv(r"C:\Users\ANUBHAV\Data_Analytics\DAP\Data_Gathering\Datasets\aug_train.csv" ,  dtype = {'target' : int}).info()

<class 'pandas.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   enrollee_id             19158 non-null  int64
 1   city                    19158 non-null  str
 2   city_development_index  19158 non-null  float64
 3   gender                  14650 non-null  str
 4   relevent_experience     19158 non-null  str
 5   enrolled_university     18772 non-null  str
 6   education_level         18698 non-null  str
 7   major_discipline        16345 non-null  str
 8   experience              19093 non-null  str
 9   company_size            13220 non-null  str
 10  company_type            13018 non-null  str
 11  last_new_job            18735 non-null  str
 12  training_hours          19158 non-null  int64
 13  target                  19158 non-null  int64
dtypes: float64(1), int64(3), str(10)
memory usage: 3.4 MB

## 12. Handelling Dates :

In [49]:
# --> agar data mai date column ko default as a string pass kiya gaya hota hai , toh usse ham date ke function ko access nhi krr skte
#     isliye hame usko date mai convert krna pdta hai. 
# --> Ex :

In [50]:
pd.read_csv(r"C:\Users\ANUBHAV\Data_Analytics\DAP\Data_Gathering\Datasets\IPL Matches 2008-2020.csv").info()   #--> date as a 'str' use ho rha hai.

pd.read_csv(r"C:\Users\ANUBHAV\Data_Analytics\DAP\Data_Gathering\Datasets\IPL Matches 2008-2020.csv" , parse_dates = ['date'] ).info()

<class 'pandas.DataFrame'>
RangeIndex: 816 entries, 0 to 815
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               816 non-null    int64
 1   city             803 non-null    str
 2   date             816 non-null    str
 3   player_of_match  812 non-null    str
 4   venue            816 non-null    str
 5   neutral_venue    816 non-null    int64
 6   team1            816 non-null    str
 7   team2            816 non-null    str
 8   toss_winner      816 non-null    str
 9   toss_decision    816 non-null    str
 10  winner           812 non-null    str
 11  result           812 non-null    str
 12  result_margin    799 non-null    float64
 13  eliminator       812 non-null    str
 14  method           19 non-null     str
 15  umpire1          816 non-null    str
 16  umpire2          816 non-null    str
dtypes: float64(1), int64(2), str(14)
memory usage: 233.0 KB
<class 'pandas.DataFrame'>
RangeIndex: 816 entries, 0 to 815
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               816 non-null    int64
 1   city             803 non-null    str
 2   date             816 non-null    datetime64[us]
 3   player_of_match  812 non-null    str
 4   venue            816 non-null    str
 5   neutral_venue    816 non-null    int64
 6   team1            816 non-null    str
 7   team2            816 non-null    str
 8   toss_winner      816 non-null    str
 9   toss_decision    816 non-null    str
 10  winner           812 non-null    str
 11  result           812 non-null    str
 12  result_margin    799 non-null    float64
 13  eliminator       812 non-null    str
 14  method           19 non-null     str
 15  umpire1          816 non-null    str
 16  umpire2          816 non-null    str
dtypes: datetime64[us](1), float64(1), int64(2), str(13)
memory usage: 225.0 KB

## 13. Convertors :

In [51]:
# --> Convertors ak aisa method hai jiska main use hota hai data ke kisi column ko explicitely 
#     kisi function ka use krke transform krna.

# --> Ex : 
# Ipl dataset mai team1 name ke column mai team ka full name likha hai like ( Royal challengers Bengalore ) ,
# par hame chaiye sirf iska short form ( RCB ) toh iske liye converters use hoga.

In [52]:
# pd.read_csv(r"C:\Users\ANUBHAV\Data_Analytics\DAP\Data_Gathering\Datasets\IPL Matches 2008-2020.csv")

# Explicit function : 

def rename(name):
    if name == "Royal Challengers Bangalore":
        return "RCB" 
    else:
        return name

In [54]:
rename("Royal Challengers Bangalore")

'RCB'

In [21]:
# Implimentation : 

pd.read_csv(r"C:\Users\ANUBHAV\Data_Analytics\DAP\Data_Gathering\Datasets\IPL Matches 2008-2020.csv" , converters = {'team1': rename})

,id,city,date,player_of_match,venue,neutral_venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,method,umpire1,umpire2
0,335982,Bangalore,2008-04-18,BB McCullum,M Chinnaswamy Stadium,0,RCB,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,Chandigarh,2008-04-19,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",0,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,NaN,MR Benson,SL Shastri
2,335984,Delhi,2008-04-19,MF Maharoof,Feroz Shah Kotla,0,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,Mumbai,2008-04-20,MV Boucher,Wankhede Stadium,0,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,NaN,SJ Davis,DJ Harper
4,335986,Kolkata,2008-04-20,DJ Hussey,Eden Gardens,0,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,NaN,BF Bowden,K Hariharan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
811,1216547,Dubai,2020-09-28,AB de Villiers,Dubai International Cricket Stadium,0,RCB,Mumbai Indians,Mumbai Indians,field,Royal Challengers Bangalore,tie,NaN,Y,NaN,Nitin Menon,PR Reiffel
812,1237177,Dubai,2020-11-05,JJ Bumrah,Dubai International Cricket Stadium,0,Mumbai Indians,Delhi Capitals,Delhi Capitals,field,Mumbai Indians,runs,57.0,N,NaN,CB Gaffaney,Nitin Menon
813,1237178,Abu Dhabi,2020-11-06,KS Williamson,Sheikh Zayed Stadium,0,RCB,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,6.0,N,NaN,PR Reiffel,S Ravi
814,1237180,Abu Dhabi,2020-11-08,MP Stoinis,Sheikh Zayed Stadium,0,Delhi Capitals,Sunrisers Hyderabad,Delhi Capitals,bat,Delhi Capitals,runs,17.0,N,NaN,PR Reiffel,S Ravi
815,1237181,Dubai,2020-11-10,TA Boult,Dubai International Cricket Stadium,0,Delhi Capitals,Mumbai Indians,Delhi Capitals,bat,Mumbai Indians,wickets,5.0,N,NaN,CB Gaffaney,Nitin Menon

## 14. na_values parameter :

In [56]:
# --> ye missing data ya jaha kuch aisa data ho like ( - , # , % ) isse' NaN' se replace krne ke liye use hota hai. 
# --> Ex :

In [57]:
pd.read_csv(r"C:\Users\ANUBHAV\Data_Analytics\DAP\Data_Gathering\Datasets\aug_train.csv" , na_values = ['Male'])

#--> ye jaha Male ya bracket ke ander given jitni bhi values hongi
#    column mai uski jagah NAN replace krr dega.

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
0,8949,city_103,0.920,NaN,Has relevent experience,no_enrollment,Graduate,STEM,>20,NaN,NaN,1,36,1.0
1,29725,city_40,0.776,NaN,No relevent experience,no_enrollment,Graduate,STEM,15,50-99,Pvt Ltd,>4,47,0.0
2,11561,city_21,0.624,NaN,No relevent experience,Full time course,Graduate,STEM,5,NaN,NaN,never,83,0.0
3,33241,city_115,0.789,NaN,No relevent experience,NaN,Graduate,Business Degree,<1,NaN,Pvt Ltd,never,52,1.0
4,666,city_162,0.767,NaN,Has relevent experience,no_enrollment,Masters,STEM,>20,50-99,Funded Startup,4,8,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19153,7386,city_173,0.878,NaN,No relevent experience,no_enrollment,Graduate,Humanities,14,NaN,NaN,1,42,1.0
19154,31398,city_103,0.920,NaN,Has relevent experience,no_enrollment,Graduate,STEM,14,NaN,NaN,4,52,1.0
19155,24576,city_103,0.920,NaN,Has relevent experience,no_enrollment,Graduate,STEM,>20,50-99,Pvt Ltd,4,44,0.0
19156,5756,city_65,0.802,NaN,Has relevent experience,no_enrollment,High School,NaN,<1,500-999,Pvt Ltd,2,97,0.0
19157,23834,city_67,0.855,NaN,No relevent experience,no_enrollment,Primary School,NaN,2,NaN,NaN,1,127,0.0

## 15. Loading a huge dataset in chunks :

In [23]:
# --> ye large amount of dataset ko defined rows(chunks) mai divide krta hai.

In [71]:
dfs = pd.read_csv(r"C:\Users\ANUBHAV\Data_Analytics\DAP\Data_Gathering\Datasets\aug_train.csv" , chunksize = 5000)

for chunks in dfs:
    print(chunks.info())

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   enrollee_id             5000 non-null   int64
 1   city                    5000 non-null   str
 2   city_development_index  5000 non-null   float64
 3   gender                  3887 non-null   str
 4   relevent_experience     5000 non-null   str
 5   enrolled_university     4893 non-null   str
 6   education_level         4882 non-null   str
 7   major_discipline        4276 non-null   str
 8   experience              4989 non-null   str
 9   company_size            3429 non-null   str
 10  company_type            3379 non-null   str
 11  last_new_job            4896 non-null   str
 12  training_hours          5000 non-null   int64
 13  target                  5000 non-null   float64
dtypes: float64(2), int64(2), str(10)
memory usage: 902.7 KB
None
<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 5000 to 9999
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   enrollee_id             5000 non-null   int64
 1   city                    5000 non-null   str
 2   city_development_index  5000 non-null   float64
 3   gender                  3801 non-null   str
 4   relevent_experience     5000 non-null   str
 5   enrolled_university     4910 non-null   str
 6   education_level         4882 non-null   str
 7   major_discipline        4245 non-null   str
 8   experience              4982 non-null   str
 9   company_size            3459 non-null   str
 10  company_type            3436 non-null   str
 11  last_new_job            4880 non-null   str
 12  training_hours          5000 non-null   int64
 13  target                  5000 non-null   float64
dtypes: float64(2), int64(2), str(10)
memory usage: 903.0 KB
None
<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 10000 to 14999
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   enrollee_id             5000 non-null   int64
 1   city                    5000 non-null   str
 2   city_development_index  5000 non-null   float64
 3   gender                  3775 non-null   str
 4   relevent_experience     5000 non-null   str
 5   enrolled_university     4897 non-null   str
 6   education_level         4892 non-null   str
 7   major_discipline        4287 non-null   str
 8   experience              4984 non-null   str
 9   company_size            3445 non-null   str
 10  company_type            3356 non-null   str
 11  last_new_job            4890 non-null   str
 12  training_hours          5000 non-null   int64
 13  target                  5000 non-null   float64
dtypes: float64(2), int64(2), str(10)
memory usage: 902.6 KB
None
<class 'pandas.DataFrame'>
RangeIndex: 4158 entries, 15000 to 19157
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   enrollee_id             4158 non-null   int64
 1   city                    4158 non-null   str
 2   city_development_index  4158 non-null   float64
 3   gender                  3187 non-null   str
 4   relevent_experience     4158 non-null   str
 5   enrolled_university     4072 non-null   str
 6   education_level         4042 non-null   str
 7   major_discipline        3537 non-null   str
 8   experience              4138 non-null   str
 9   company_size            2887 non-null   str
 10  company_type            2847 non-null   str
 11  last_new_job            4069 non-null   str
 12  training_hours          4158 non-null   int64
 13  target                  4158 non-null   float64
dtypes: float64(2), int64(2), str(10)
memory usage: 750.8 KB
None