In [1]:
## :: Multi-Index Objects :

In [2]:
import numpy as np
import pandas as pd

## Series is 1D and DataFrames are 2D objects :

--> But Why? 

--> And what exactly is index?

In [4]:
## Seires mai hame koi ak single data fetch karne ke liye one - piece of information dena pdta hai.

## Dataframe mai hame koi ak single data fetch karne ke liye two - piece of information dena pdta hai.

In [5]:
## can we have multiple index in Series ? Let's try " :

index_val = [('cse',2019),('cse',2020),('cse',2021),('cse',2022),('ece',2019),('ece',2020),('ece',2021),('ece',2022)]
a = pd.Series([1,2,3,4,5,6,7,8] , index=index_val)
a

(cse, 2019)    1
(cse, 2020)    2
(cse, 2021)    3
(cse, 2022)    4
(ece, 2019)    5
(ece, 2020)    6
(ece, 2021)    7
(ece, 2022)    8
dtype: int64

In [6]:
## Fetching value 4 :

a[('cse' , 2022)]

np.int64(4)

In [7]:
a[('cse')]  # Error 

#--> Solution : multiindex series(also known as Hierarchial Indexing).
#--> multiple index levels within a single index.

KeyError: 'cse'

In [8]:
## How to create muli-index object :

In [12]:
# 1. pd.MultiIndex.from_tuples() :

index_val = [('cse',2019),('cse',2020),('cse',2021),('cse',2022),('ece',2019),('ece',2020),('ece',2021),('ece',2022)]
multiindex = pd.MultiIndex.from_tuples(index_val)
multiindex.levels[0]   # output : Index(['cse', 'ece'], dtype='str')

multiindex.levels[1]   # output : Index([2019, 2020, 2021, 2022], dtype='int64')

Index([2019, 2020, 2021, 2022], dtype='int64')

In [13]:
# 2. pd.MultiIndex.from_product() :

index_val = [('cse',2019),('cse',2020),('cse',2021),('cse',2022),('ece',2019),('ece',2020),('ece',2021),('ece',2022)]
multiindex = pd.MultiIndex.from_product([ ['cse' , 'ece'] , [2019 ,2020 , 2021 , 2022] ])
multiindex

MultiIndex([('cse', 2019),
            ('cse', 2020),
            ('cse', 2021),
            ('cse', 2022),
            ('ece', 2019),
            ('ece', 2020),
            ('ece', 2021),
            ('ece', 2022)],
           )

In [16]:
## Creating a series with multiindex object :

s = pd.Series( [1,2,3,4,5,6,7,8] , index = multiindex)
s

cse  2019    1
     2020    2
     2021    3
     2022    4
ece  2019    5
     2020    6
     2021    7
     2022    8
dtype: int64

In [18]:
## Fetching items from a multiindex Series : 

s[('cse' , 2022)]

s[('cse')]

2019    1
2020    2
2021    3
2022    4
dtype: int64

In [21]:
## Unstack : 

# --> Iss method se hum kisi bhi multiindex Series ko dataframe mai convert krr skte hai. 

temp = s.unstack()
temp

     2019  2020  2021  2022
cse     1     2     3     4
ece     5     6     7     8

In [23]:
## stack : 

#--> Ye kisi bhi dataframe ko multi-index series mai convert krr deta hai.

temp.stack()

cse  2019    1
     2020    2
     2021    3
     2022    4
ece  2019    5
     2020    6
     2021    7
     2022    8
dtype: int64

In [25]:
## Why should we use Multi-index Series : 

#--> Higher dimension data ko like( 5d , 10d , 15d ) ko lower dimension like(series and dataframe) mai represent krwa skte hai.

In [ ]:
######################################################################################################################################################

In [26]:
## Multi-index DataFrame :

In [28]:
branch_df1 = pd.DataFrame(
    [
        [1,2],
        [3,4],
        [5,6],
        [7,8],
        [9,10],
        [11,12],
        [13,14],
        [15,16],
    ],
    index = multiindex,
    columns = ['avg_package','students']
)

branch_df1

          avg_package  students
cse 2019            1         2
    2020            3         4
    2021            5         6
    2022            7         8
ece 2019            9        10
    2020           11        12
    2021           13        14
    2022           15        16

In [30]:
branch_df1.loc['cse']
branch_df1.loc['ece']

      avg_package  students
2019            9        10
2020           11        12
2021           13        14
2022           15        16

In [32]:
branch_df1['students']
branch_df1['avg_package']

cse  2019     1
     2020     3
     2021     5
     2022     7
ece  2019     9
     2020    11
     2021    13
     2022    15
Name: avg_package, dtype: int64

In [33]:
# multiindex df from columns perspective
branch_df2 = pd.DataFrame(
    [
        [1,2,0,0],
        [3,4,0,0],
        [5,6,0,0],
        [7,8,0,0],
    ],
    index = [2019,2020,2021,2022],
    columns = pd.MultiIndex.from_product([['delhi','mumbai'],['avg_package','students']])
)

branch_df2

           delhi               mumbai
     avg_package students avg_package students
2019           1        2           0        0
2020           3        4           0        0
2021           5        6           0        0
2022           7        8           0        0

In [35]:
branch_df2['delhi']
branch_df2['mumbai']

      avg_package  students
2019            0         0
2020            0         0
2021            0         0
2022            0         0

In [37]:
branch_df2['delhi']['avg_package']
branch_df2['mumbai']['avg_package']

2019    0
2020    0
2021    0
2022    0
Name: avg_package, dtype: int64

In [39]:
branch_df2.loc[2019]
branch_df2.loc[2020]

delhi   avg_package    3
        students       4
mumbai  avg_package    0
        students       0
Name: 2020, dtype: int64

In [40]:
# Multiindex df in terms of both cols and index

branch_df3 = pd.DataFrame(
    [
        [1,2,0,0],
        [3,4,0,0],
        [5,6,0,0],
        [7,8,0,0],
        [9,10,0,0],
        [11,12,0,0],
        [13,14,0,0],
        [15,16,0,0],
    ],
    index = multiindex,
    columns = pd.MultiIndex.from_product([['delhi','mumbai'],['avg_package','students']])
)

branch_df3

               delhi               mumbai
         avg_package students avg_package students
cse 2019           1        2           0        0
    2020           3        4           0        0
    2021           5        6           0        0
    2022           7        8           0        0
ece 2019           9       10           0        0
    2020          11       12           0        0
    2021          13       14           0        0
    2022          15       16           0        0

## Stacking And Unstacking :