In [1]:
import pandas as pd

In [5]:
dict1 = {
    'Name' : ['Priyang' , 'Aadhya' , 'krisha' , 'Vedant' , 'Parshv' , 'Mittal' , 'Archana'],
    'Marks' : [98 , 89 , 99 , 87 , 90 , 83 , 99],
    'Gender' : ['Male' , 'Female' , 'Female' , 'Male' , 'Male' , 'Female' , 'Female']
}

df1 = pd.DataFrame(dict1)
df1

      Name  Marks  Gender
0  Priyang     98    Male
1   Aadhya     89  Female
2   krisha     99  Female
3   Vedant     87    Male
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99  Female

## 1. Display Top 3 Rows of the Dataset :

In [7]:
df1.head(3)

      Name  Marks  Gender
0  Priyang     98    Male
1   Aadhya     89  Female
2   krisha     99  Female

## 2. Display last 3 Rows of the Dataset :

In [8]:
df1.tail(3)

      Name  Marks  Gender
4   Parshv     90    Male
5   Mittal     83  Female
6  Archana     99  Female

## 3. Find Shape of Our Dataset (Number of Rows & Number of Columns) :

In [9]:
df1.shape

(7, 3)

In [10]:
print("the total row of df1 : " , df1.shape[0])
print("the total Column of df1 : " , df1.shape[1])

the total row of df1 :  7
the total Column of df1 :  3

## 4. Get Information About Our Dataset Like Total Number Rows, Total Number of Columns, Datatypes of Each Column And Memory Requirement :

In [11]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    7 non-null      str
 1   Marks   7 non-null      int64
 2   Gender  7 non-null      str
dtypes: int64(1), str(2)
memory usage: 380.0 bytes

## 5.Check Null Values In The Dataset :

In [13]:
df1.isnull().sum()

Name      0
Marks     0
Gender    0
dtype: int64

## 6. Get Overall Statistics About The Dataframe :

In [19]:
df1.describe()

           Marks
count   7.000000
mean   92.142857
std     6.491753
min    83.000000
25%    88.000000
50%    90.000000
75%    98.500000
max    99.000000

## 7.Find Unique Values From The Gender Column :

In [24]:
df1['Gender'].unique()

<ArrowStringArray>
['Male', 'Female']
Length: 2, dtype: str

## 8. Find the Number of Unique values from the Gender column :

In [27]:
len(df1['Gender'].unique())

2

In [28]:
df1['Gender'].nunique()

2

## 9. Display Count of Unique Values In Gender Column :

In [29]:
df1['Gender'].value_counts()

Gender
Female    4
Male      3
Name: count, dtype: int64

## 10. Find Total Number of Students Having Marks Between 90 To 100 (Inclusive) Using Between Method :

In [38]:
df1[ (df1['Marks'] > 90)  &  (df1['Marks'] < 100) ]

      Name  Marks  Gender
0  Priyang     98    Male
2   krisha     99  Female
6  Archana     99  Female

In [46]:
df1[df1['Marks'].between(90 , 100)]

      Name  Marks  Gender
0  Priyang     98    Male
2   krisha     99  Female
4   Parshv     90    Male
6  Archana     99  Female

In [48]:
sum(df1['Marks'].between(90 , 100))

4

## 11. Find Average Marks :

In [50]:
df1['Marks'].mean()

np.float64(92.14285714285714)

## 12. Apply Method :

In [57]:
def marks(num):
    return num/2

In [58]:
df1['Half_Marks'] = df1['Marks'].apply(marks)

df1['Half_Marks']

0    49.0
1    44.5
2    49.5
3    43.5
4    45.0
5    41.5
6    49.5
Name: Half_Marks, dtype: float64

In [63]:
df1['Name'].apply(len)

0    7
1    6
2    6
3    6
4    6
5    6
6    7
Name: Name, dtype: int64

In [65]:
df1['Marks'].apply(lambda x : x//4)

0    24
1    22
2    24
3    21
4    22
5    20
6    24
Name: Marks, dtype: int64

## 13. Map Function :

In [69]:
df1['Male_Female'] = df1['Gender'].map({
    'Male' : 1,
    'Female' : 0
})

In [70]:
df1

      Name  Marks  Gender  Half_Marks  Male_Female
0  Priyang     98    Male        49.0            1
1   Aadhya     89  Female        44.5            0
2   krisha     99  Female        49.5            0
3   Vedant     87    Male        43.5            1
4   Parshv     90    Male        45.0            1
5   Mittal     83  Female        41.5            0
6  Archana     99  Female        49.5            0

## 14. Drop the Column(s) :

In [76]:
df1.drop('Male_Female' , axis = 1 , inplace = True)

In [77]:
df1

      Name  Marks  Gender  Half_Marks
0  Priyang     98    Male        49.0
1   Aadhya     89  Female        44.5
2   krisha     99  Female        49.5
3   Vedant     87    Male        43.5
4   Parshv     90    Male        45.0
5   Mittal     83  Female        41.5
6  Archana     99  Female        49.5

## 15. Print Name of the Columns :

In [78]:
df1.columns

Index(['Name', 'Marks', 'Gender', 'Half_Marks'], dtype='str')

In [79]:
df1.index

RangeIndex(start=0, stop=7, step=1)

## 16. Sort The Dataframe As Per The Marks Column :

In [83]:
df1.sort_values(['Marks' , 'Half_Marks' ], ascending = False)

      Name  Marks  Gender  Half_Marks
2   krisha     99  Female        49.5
6  Archana     99  Female        49.5
0  Priyang     98    Male        49.0
4   Parshv     90    Male        45.0
1   Aadhya     89  Female        44.5
3   Vedant     87    Male        43.5
5   Mittal     83  Female        41.5

## 17. Display Name & Marks of The Female Students :

In [89]:
df1[df1['Gender'] == 'Female'][ ['Name' , 'Marks'] ]

      Name  Marks
1   Aadhya     89
2   krisha     99
5   Mittal     83
6  Archana     99