In [2]:
# install pandas

In [3]:
!pip install pandas

Requirement already satisfied: pandas in C:\Users\ANUBHAV\AppData\Local\Programs\Python\Python314\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\ANUBHAV\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\ANUBHAV\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\ANUBHAV\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\ANUBHAV\AppData\Local\Programs\Python\Python314\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
# import pandas 

import pandas as pd

In [5]:
pd.__version__

'3.0.3'

In [6]:
#Dataframe : tables ko dataframe kahte hai :

In [7]:
# Topics :

#

In [8]:
# 1. Create Dataframe:

In [9]:

import pandas as pd
df = pd.DataFrame([11 , 22 ,33 , 44] , columns = ['Col_Name'])
print(df)

   Col_Name
0        11
1        22
2        33
3        44

In [10]:
print(type(df))

<class 'pandas.DataFrame'>

In [11]:
data =  {
    'Name' : ['Anubhav' , 'Div' , 'Sakshi' , 'Aryan'] ,
    'age'  : [21 ,24 ,22 , 23],
    'Gender' : ['male' , 'male' , 'Female' , 'male']   
}

In [12]:
df = pd.DataFrame(data)
print(df)
type(df)

      Name  age  Gender
0  Anubhav   21    male
1      Div   24    male
2   Sakshi   22  Female
3    Aryan   23    male

pandas.DataFrame

In [13]:
# 2. Basic Dataframe Understanding :

In [14]:
# :-->  df.head(2) : printing the first two rows.

 df.head(2)

IndentationError: unexpected indent (535561790.py, line 3)

In [ ]:
# :-->  df.tail(2) : printing the last two rows.

 df.tail(2)

In [ ]:
# :--> df.shape : printing the shape of DataFrame ( 4 rows , 3 columns ).

df.shape

In [ ]:
# :--> df.columns : printing the all column name present : 

df.columns

In [ ]:
#:--> df.rename() : pahli baat toh ye hai ki iska use hota hai column name ko change krne ke liye , dusri baat ye hai ki ye original DataFrame
# ko change nhi krta hai , hame uss nayi changed column vali table ko ak naye variable mai store krke rkhna hota hai.

df1 = df.rename( columns = {'age' : 'Age'})
print(df)

print(" " * 50)
print(df1)

In [ ]:
# NOTE: Existing DataFrame mai change krne ke liye hame ak argument ka use krna hota hai jo default mai False rhti hai , inplace = False , isko
# inplace = True krne se original DataFrame mai Column name change ho jayegi. 

print(df)

df.rename( columns = { 'age' : 'Age'} , inplace = True)

print(" " * 50)

print(df)

In [ ]:
# :--> df.info() : it gives internal details of the DataFrame. 

df.info()

In [ ]:
# :--> df.describe() : it gives the basic stastical analysis. 

df.describe()

In [ ]:
#3. Save and Load data from csv :

In [ ]:
# :--> To Save the DataFrame :   df.to_csv('file_name')

In [ ]:
df.to_csv('Test_data.csv')

In [ ]:
# NOTE : To remove the index column : 

df.to_csv('Test_data.csv' , index = False)

In [ ]:
# :--> To Load the DataFrame :  df.read_csv()

In [ ]:
load_df = pd.read_csv('Test_data.csv')
print(load_df)

In [ ]:
# 4. Rows & Columns - Selection :

In [ ]:
# :--> To select some specific  single column :- 

df[['Name']]

In [ ]:
# :-->  To select the specific two columns : 

df[['Name' , 'Age']]

In [ ]:
# :--> df.loc : lable based indexing. 

df.loc[0:2]

# NOTE : isme last index value ( 2 ) ko bhi include kiya jata hai  , standard slicing se different behaviour.

In [ ]:
df   #--> printing the entire DataFrame.

In [ ]:
# Selecting rows :

In [ ]:
# Ex_1 :

df.loc[df.Name == 'Anubhav']

In [ ]:
# Ex_2 :

df.loc[ (df.Name == 'Aryan')  &  (df.Age >= 23) ]

In [ ]:
# iloc :- index-value based

In [ ]:
df.iloc[0]

In [ ]:

df.iloc[0:2]

In [ ]:
# NOTE : It behaves like normal slicing methodology.

In [ ]:
# 5. Filter dataframe  :

In [ ]:
df['Age'] >= 23

In [ ]:
# with row details :

In [ ]:
df[df['Age'] >= 22]

In [ ]:
# storing the new dataFrame :

df_age_filter = df[df['Age'] >= 22] 

print(df_age_filter)

In [ ]:
#multiple conditions :

In [ ]:
df[(df['Age'] >= 22) & ( df['Gender'] == 'Female')]

In [ ]:
# where method :

In [ ]:
df.where(df['Age'] >= 22)

In [ ]:
#--> Using other attribute :

In [ ]:
df.where(df['Age'] >= 22  , other = 'Not Eligible')

In [ ]:
# 6. Rows & Columns - Operation ( Add , update , delete)  :

In [ ]:
df

In [ ]:
#:--> Add new column : 

df['Team']  = ['CEO' , 'CTO' , 'HR' , 'DA']
df

df['Monthly_Salary'] = [45000 , 55000 , 65000 , 75000]
df

In [ ]:
# :--> column by performing calculations :

In [ ]:
df['Bonus'] = df['Monthly_Salary'] * 0.2
df

In [ ]:
df['Total_Salary'] = df['Monthly_Salary'] + df['Bonus']
df

In [ ]:
#:---->  Adding rows :

In [ ]:
df.loc[len(df)] = ['Aditi' , 22 ,'Female' , 'Marketing' ,  66000 ,  4000 , 70000]
df

In [ ]:
len(df)

In [ ]:
# :--> update value :

df.loc[0 , 'Age'] = 22
df

In [ ]:
df

In [ ]:
#-->  delete value : row[default] and columns value :

In [ ]:
df = df.drop(df[df.Name == 'Aditi'].index) #--> drop row  , axis = 0 
df

In [ ]:
df = df.drop('Total_Salary' , axis = 1)
df

In [ ]:
# :--> Sorting :

In [ ]:
df.sort_values('Monthly_Salary')
# :--> Ascending order:

In [ ]:
# :-> desecending order:

In [ ]:
df.sort_values('Monthly_Salary' , ascending = False)

In [ ]:
# 7. Working with date value :

In [22]:
df['DOJ'] = ['2024-01-01' , '2024-01-15' , '2024-03-28' , '2024-03-03']
df

      Name  age  Gender         DOJ
0  Anubhav   21    male  2024-01-01
1      Div   24    male  2024-01-15
2   Sakshi   22  Female  2024-03-28
3    Aryan   23    male  2024-03-03

In [ ]:
# :--> Changing the data type of date time :

In [24]:
df['DOJ'].dtype

In [25]:
df['DOJ'] = pd.to_datetime(df['DOJ'])

In [26]:
df['DOJ'].dtype

dtype('<M8[us]')

In [27]:
df1 = df

In [28]:
df1

      Name  age  Gender        DOJ
0  Anubhav   21    male 2024-01-01
1      Div   24    male 2024-01-15
2   Sakshi   22  Female 2024-03-28
3    Aryan   23    male 2024-03-03

In [30]:
df1['DOJ2'] = ['01-01-2025' , '15-01-2025' , '28-03-2025' , '03-03-2025']
df1

      Name  age  Gender        DOJ        DOJ2
0  Anubhav   21    male 2024-01-01  01-01-2025
1      Div   24    male 2024-01-15  15-01-2025
2   Sakshi   22  Female 2024-03-28  28-03-2025
3    Aryan   23    male 2024-03-03  03-03-2025

In [31]:
df1['DOJ2'].dtype

In [33]:
df1['DOJ2'] = pd.to_datetime(df1['DOJ2'])

ValueError: time data "15-01-2025" doesn't match format "%m-%d-%Y". You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [ ]:
# NOTE : For solving this error , we have to use format attribute.

In [34]:
df1['DOJ2'] = pd.to_datetime(df1['DOJ2'] , format = '%d-%m-%Y')

In [35]:
df1['DOJ2'].dtype

dtype('<M8[us]')

In [ ]:
# deleting the DOJ2 column :

In [37]:
df = df.drop('DOJ2' , axis = 1)
df

      Name  age  Gender        DOJ
0  Anubhav   21    male 2024-01-01
1      Div   24    male 2024-01-15
2   Sakshi   22  Female 2024-03-28
3    Aryan   23    male 2024-03-03

In [ ]:
#Extract year , month , weekdays , day :

In [38]:
df['DOJ'].dt.year  #--> year

0    2024
1    2024
2    2024
3    2024
Name: DOJ, dtype: int32

In [39]:
df['DOJ'].dt.month  #--> month

0    1
1    1
2    3
3    3
Name: DOJ, dtype: int32

In [40]:
df['DOJ'].dt.day   #--> day

0     1
1    15
2    28
3     3
Name: DOJ, dtype: int32

In [41]:
df['DOJ'].dt.day_name()  #--> weekdays

0      Monday
1      Monday
2    Thursday
3      Sunday
Name: DOJ, dtype: str

In [42]:
#creating month column:

df['Month'] = df['DOJ'].dt.month
df

      Name  age  Gender        DOJ  Month
0  Anubhav   21    male 2024-01-01      1
1      Div   24    male 2024-01-15      1
2   Sakshi   22  Female 2024-03-28      3
3    Aryan   23    male 2024-03-03      3

In [43]:
# calculating the probation[training] period of employee:

In [44]:
df['DOJ'] + pd.Timedelta(days = 90)

0   2024-03-31
1   2024-04-14
2   2024-06-26
3   2024-06-01
Name: DOJ, dtype: datetime64[us]

In [ ]:
# 8. Handelling missing values:

In [45]:
df

      Name  age  Gender        DOJ  Month
0  Anubhav   21    male 2024-01-01      1
1      Div   24    male 2024-01-15      1
2   Sakshi   22  Female 2024-03-28      3
3    Aryan   23    male 2024-03-03      3

In [ ]:
# :--> Creating null values :

In [46]:
df.isnull()    #--> gives true at the place of null value.

    Name    age  Gender    DOJ  Month
0  False  False   False  False  False
1  False  False   False  False  False
2  False  False   False  False  False
3  False  False   False  False  False

In [47]:
#making the salary of Anubhav as nan :

In [51]:
df = df.drop('Salary'  , axis = 1)
df

      Name  age  Gender        DOJ  Month
0  Anubhav   21    male 2024-01-01      1
1      Div   24    male 2024-01-15      1
2   Sakshi   22  Female 2024-03-28      3
3    Aryan   23    male 2024-03-03      3

In [53]:
df['Salary'] = [58000 , 55000 , 64000 , 86000]
df

      Name  age  Gender        DOJ  Month  Salary
0  Anubhav   21    male 2024-01-01      1   58000
1      Div   24    male 2024-01-15      1   55000
2   Sakshi   22  Female 2024-03-28      3   64000
3    Aryan   23    male 2024-03-03      3   86000

In [54]:

import numpy as np
df.loc[df.Name == 'Anubhav' , 'Salary'] = np.nan
df

      Name  age  Gender        DOJ  Month   Salary
0  Anubhav   21    male 2024-01-01      1      NaN
1      Div   24    male 2024-01-15      1  55000.0
2   Sakshi   22  Female 2024-03-28      3  64000.0
3    Aryan   23    male 2024-03-03      3  86000.0

In [56]:
df.isnull()

    Name    age  Gender    DOJ  Month  Salary
0  False  False   False  False  False    True
1  False  False   False  False  False   False
2  False  False   False  False  False   False
3  False  False   False  False  False   False

In [ ]:
# checking null value at the large dataset :

In [57]:
df.isnull().sum()

Name      0
age       0
Gender    0
DOJ       0
Month     0
Salary    1
dtype: int64

In [ ]:
#To remove the null value :

In [58]:
df.fillna(0)

      Name  age  Gender        DOJ  Month   Salary
0  Anubhav   21    male 2024-01-01      1      0.0
1      Div   24    male 2024-01-15      1  55000.0
2   Sakshi   22  Female 2024-03-28      3  64000.0
3    Aryan   23    male 2024-03-03      3  86000.0

In [59]:
df

      Name  age  Gender        DOJ  Month   Salary
0  Anubhav   21    male 2024-01-01      1      NaN
1      Div   24    male 2024-01-15      1  55000.0
2   Sakshi   22  Female 2024-03-28      3  64000.0
3    Aryan   23    male 2024-03-03      3  86000.0

In [60]:
df.loc[df.Name == 'Anubhav' , 'Salary'] = 58000
df

      Name  age  Gender        DOJ  Month   Salary
0  Anubhav   21    male 2024-01-01      1  58000.0
1      Div   24    male 2024-01-15      1  55000.0
2   Sakshi   22  Female 2024-03-28      3  64000.0
3    Aryan   23    male 2024-03-03      3  86000.0

In [62]:
df['Team'] = ['DA' , 'SDE',  'AI/ML' , 'SE']
df

      Name  age  Gender        DOJ  Month   Salary   Team
0  Anubhav   21    male 2024-01-01      1  58000.0     DA
1      Div   24    male 2024-01-15      1  55000.0    SDE
2   Sakshi   22  Female 2024-03-28      3  64000.0  AI/ML
3    Aryan   23    male 2024-03-03      3  86000.0     SE

In [ ]:
# 9. Aggregation and group by :

In [63]:
df['Team'].value_counts()  #--> checking how many employees are there in each Team.

Team
DA       1
SDE      1
AI/ML    1
SE       1
Name: count, dtype: int64

In [64]:
df[ df['Month'] == 1 ].value_counts()   #--> only month == 1 se related employees.

Name     age  Gender  DOJ         Month  Salary   Team
Anubhav  21   male    2024-01-01  1      58000.0  DA      1
Div      24   male    2024-01-15  1      55000.0  SDE     1
Name: count, dtype: int64

In [ ]:
#checking the total sum of salary in 1 month :

In [65]:
df.groupby('Month')['Salary'].sum()

Month
1    113000.0
3    150000.0
Name: Salary, dtype: float64

In [ ]:
#checking the total avg[mean] of salary in 1 month :

In [67]:
df.groupby('Month')['Salary'].mean()

Month
1    56500.0
3    75000.0
Name: Salary, dtype: float64

In [ ]:
# applying aggregation on the multiple column  :

In [69]:
df.groupby('Month').agg({'Salary' : 'mean' , 'Name' : 'count'})

        Salary  Name
Month
1      56500.0     2
3      75000.0     2

In [ ]:
# 10. Concatenate and Merge Dataframe ( JOINS ) :

In [70]:
df1 = pd.DataFrame( { 'ID' : [1,2,3] , 'Name' : ['A' , 'B' , 'C'] } )
df1

   ID Name
0   1    A
1   2    B
2   3    C

In [71]:
df2 = pd.DataFrame( { 'ID' : [1,2,2,4] , 'Score' : [88 , 96 , 77 , 79] } )
df2

   ID  Score
0   1     88
1   2     96
2   2     77
3   4     79

In [ ]:
# concatenate :

In [72]:
pd.concat([df1 , df2] , axis = 0)  #-->vertical / row level / top on top.

   ID Name  Score
0   1    A    NaN
1   2    B    NaN
2   3    C    NaN
0   1  NaN   88.0
1   2  NaN   96.0
2   2  NaN   77.0
3   4  NaN   79.0

In [73]:
pd.concat([df1 , df2] , axis = 0)  #--> horizontal / column level / side by side.

   ID Name  Score
0   1    A    NaN
1   2    B    NaN
2   3    C    NaN
0   1  NaN   88.0
1   2  NaN   96.0
2   2  NaN   77.0
3   4  NaN   79.0

In [ ]:
# merge / Join :

In [74]:
pd.merge(df1 , df2 , how = 'inner' , on = 'ID')

   ID Name  Score
0   1    A     88
1   2    B     96
2   2    B     77

In [ ]:
# join when common column have different name :

In [75]:
pd.merge(df1 , df2 , how = 'inner' , left_on = 'ID' , right_on = 'ID')

   ID Name  Score
0   1    A     88
1   2    B     96
2   2    B     77

In [76]:
# 11. AI and ChatGPT :

In [77]:
df

      Name  age  Gender        DOJ  Month   Salary   Team
0  Anubhav   21    male 2024-01-01      1  58000.0     DA
1      Div   24    male 2024-01-15      1  55000.0    SDE
2   Sakshi   22  Female 2024-03-28      3  64000.0  AI/ML
3    Aryan   23    male 2024-03-03      3  86000.0     SE

In [ ]:
# use prompt engineering and perform operations.