In [ ]:
# install pandas

In [1]:
!pip install pandas

Collecting pandas
  Downloading pandas-3.0.3-cp314-cp314-win_amd64.whl.metadata (19 kB)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\ANUBHAV\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\ANUBHAV\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\ANUBHAV\AppData\Local\Programs\Python\Python314\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\ANUBHAV\AppData\Local\Programs\Python\Python314\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.3-cp314-cp314-win_amd64.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.9 MB 962.7 kB/s eta 0:00:10
   -- ------------------------------------- 0.5/9.9 MB 962.7 kB/s eta 0:00:10
   --- ------------------------------------ 0.8/9.9 MB 988.9 kB/s eta 0:00:10
   ----- ---------------------------------- 1.3/9.9 MB 1.1 MB/s eta 0:00:08
   ------ --------------------------------- 1.6/9.9 MB 1.2 MB/s eta 0:00:08
   ------- -------------------------------- 1.8/9.9 MB 1.2 MB/s eta 0:00:07
   -------- ------------------------------- 2.1/9.9 MB 1.3 MB/s eta 0:00:07
   --------- ------------------------------ 2.4/9.9 MB 1.3 MB/s eta 0:00:06
   ---------- ----------------------------- 2.6/9.9 MB 1.3 MB/s eta 0:00:06
   ----------- ---------------------------- 2.9/9.9 MB 1.3 MB/s eta 0:00:06
   ------------ --------------------------- 3.1/9.9 MB 1.3 MB/s eta 0:00:06
   -------------- ------------------------- 3.7/9.9 MB 1.3 MB/s eta 0:00:05
   --------------- ------------------------ 3.9/9.9 MB 1.4 MB/s eta 0:00:05
   ------------------ --------------------- 4.5/9.9 MB 1.4 MB/s eta 0:00:04
   ------------------- -------------------- 4.7/9.9 MB 1.4 MB/s eta 0:00:04
   -------------------- ------------------- 5.0/9.9 MB 1.4 MB/s eta 0:00:04
   --------------------- ------------------ 5.2/9.9 MB 1.4 MB/s eta 0:00:04
   ----------------------- ---------------- 5.8/9.9 MB 1.4 MB/s eta 0:00:03
   ------------------------ --------------- 6.0/9.9 MB 1.5 MB/s eta 0:00:03
   -------------------------- ------------- 6.6/9.9 MB 1.5 MB/s eta 0:00:03
   --------------------------- ------------ 6.8/9.9 MB 1.5 MB/s eta 0:00:03
   ----------------------------- ---------- 7.3/9.9 MB 1.5 MB/s eta 0:00:02
   ------------------------------- -------- 7.9/9.9 MB 1.6 MB/s eta 0:00:02
   -------------------------------- ------- 8.1/9.9 MB 1.6 MB/s eta 0:00:02
   --------------------------------- ------ 8.4/9.9 MB 1.5 MB/s eta 0:00:01
   ----------------------------------- ---- 8.7/9.9 MB 1.5 MB/s eta 0:00:01
   ----------------------------------- ---- 8.7/9.9 MB 1.5 MB/s eta 0:00:01
   ------------------------------------ --- 8.9/9.9 MB 1.5 MB/s eta 0:00:01
   ------------------------------------- -- 9.2/9.9 MB 1.5 MB/s eta 0:00:01
   -------------------------------------- - 9.4/9.9 MB 1.5 MB/s eta 0:00:01
   ---------------------------------------- 9.9/9.9 MB 1.5 MB/s  0:00:06
Installing collected packages: pandas
Successfully installed pandas-3.0.3

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
# import pandas 

import pandas as pd

In [3]:
pd.__version__

'3.0.3'

In [ ]:
#Dataframe : tables ko dataframe kahte hai :

In [ ]:
# Topics :

#

In [5]:
# 1. Create Dataframe:

In [6]:

import pandas as pd
df = pd.DataFrame([11 , 22 ,33 , 44] , columns = ['Col_Name'])
print(df)

   Col_Name
0        11
1        22
2        33
3        44

In [8]:
print(type(df))

<class 'pandas.DataFrame'>

In [10]:
data =  {
    'Name' : ['Anubhav' , 'Div' , 'Sakshi' , 'Aryan'] ,
    'age'  : [21 ,24 ,22 , 23],
    'Gender' : ['male' , 'male' , 'Female' , 'male']   
}

In [13]:
df = pd.DataFrame(data)
print(df)
type(df)

      Name  age  Gender
0  Anubhav   21    male
1      Div   24    male
2   Sakshi   22  Female
3    Aryan   23    male

pandas.DataFrame

In [6]:
# 2. Basic Dataframe Understanding :

In [17]:
# :-->  df.head(2) : printing the first two rows.

 df.head(2)

      Name  age Gender
0  Anubhav   21   male
1      Div   24   male

In [18]:
# :-->  df.tail(2) : printing the last two rows.

 df.tail(2)

     Name  age  Gender
2  Sakshi   22  Female
3   Aryan   23    male

In [21]:
# :--> df.shape : printing the shape of DataFrame ( 4 rows , 3 columns ).

df.shape

(4, 3)

In [22]:
# :--> df.columns : printing the all column name present : 

df.columns

Index(['Name', 'age', 'Gender'], dtype='str')

In [25]:
#:--> df.rename() : pahli baat toh ye hai ki iska use hota hai column name ko change krne ke liye , dusri baat ye hai ki ye original DataFrame
# ko change nhi krta hai , hame uss nayi changed column vali table ko ak naye variable mai store krke rkhna hota hai.

df1 = df.rename( columns = {'age' : 'Age'})
print(df)

print(" " * 50)
print(df1)

      Name  age  Gender
0  Anubhav   21    male
1      Div   24    male
2   Sakshi   22  Female
3    Aryan   23    male

      Name  Age  Gender
0  Anubhav   21    male
1      Div   24    male
2   Sakshi   22  Female
3    Aryan   23    male

In [27]:
# NOTE: Existing DataFrame mai change krne ke liye hame ak argument ka use krna hota hai jo default mai False rhti hai , inplace = False , isko
# inplace = True krne se original DataFrame mai Column name change ho jayegi. 

print(df)

df.rename( columns = { 'age' : 'Age'} , inplace = True)

print(" " * 50)

print(df)

      Name  age  Gender
0  Anubhav   21    male
1      Div   24    male
2   Sakshi   22  Female
3    Aryan   23    male

      Name  Age  Gender
0  Anubhav   21    male
1      Div   24    male
2   Sakshi   22  Female
3    Aryan   23    male

In [28]:
# :--> df.info() : it gives internal details of the DataFrame. 

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      str
 1   Age     4 non-null      int64
 2   Gender  4 non-null      str
dtypes: int64(1), str(2)
memory usage: 228.0 bytes

In [30]:
# :--> df.describe() : it gives the basic stastical analysis. 

df.describe()

             Age
count   4.000000
mean   22.500000
std     1.290994
min    21.000000
25%    21.750000
50%    22.500000
75%    23.250000
max    24.000000

In [31]:
#3. Save and Load data from csv :

In [ ]:
# :--> To Save the DataFrame :   df.to_csv('file_name')

In [32]:
df.to_csv('Test_data.csv')

In [35]:
# NOTE : To remove the index column : 

df.to_csv('Test_data.csv' , index = False)

In [ ]:
# :--> To Load the DataFrame :  df.read_csv()

In [36]:
load_df = pd.read_csv('Test_data.csv')
print(load_df)

      Name  Age  Gender
0  Anubhav   21    male
1      Div   24    male
2   Sakshi   22  Female
3    Aryan   24    male

In [37]:
# 4. Rows & Columns - Selection :

In [39]:
# :--> To select some specific  single column :- 

df[['Name']]

      Name
0  Anubhav
1      Div
2   Sakshi
3    Aryan

In [41]:
# :-->  To select the specific two columns : 

df[['Name' , 'Age']]

      Name  Age
0  Anubhav   21
1      Div   24
2   Sakshi   22
3    Aryan   23

In [43]:
# :--> df.loc : lable based indexing. 

df.loc[0:2]

# NOTE : isme last index value ( 2 ) ko bhi include kiya jata hai  , standard slicing se different behaviour.

      Name  Age  Gender
0  Anubhav   21    male
1      Div   24    male
2   Sakshi   22  Female

In [44]:
df   #--> printing the entire DataFrame.

      Name  Age  Gender
0  Anubhav   21    male
1      Div   24    male
2   Sakshi   22  Female
3    Aryan   23    male

In [ ]:
# Selecting rows :

In [45]:
# Ex_1 :

df.loc[df.Name == 'Anubhav']

      Name  Age Gender
0  Anubhav   21   male

In [46]:
# Ex_2 :

df.loc[ (df.Name == 'Aryan')  &  (df.Age >= 23) ]

    Name  Age Gender
3  Aryan   23   male

In [ ]:
# iloc :- index-value based

In [48]:
df.iloc[0]

Name      Anubhav
Age            21
Gender       male
Name: 0, dtype: object

In [49]:

df.iloc[0:2]

      Name  Age Gender
0  Anubhav   21   male
1      Div   24   male

In [ ]:
# NOTE : It behaves like normal slicing methodology.

In [ ]:
# 5. Filter dataframe  :

In [51]:
df['Age'] >= 23

0    False
1     True
2    False
3     True
Name: Age, dtype: bool

In [ ]:
# with row details :

In [54]:
df[df['Age'] >= 22]

     Name  Age  Gender
1     Div   24    male
2  Sakshi   22  Female
3   Aryan   23    male

In [55]:
# storing the new dataFrame :

df_age_filter = df[df['Age'] >= 22] 

print(df_age_filter)

     Name  Age  Gender
1     Div   24    male
2  Sakshi   22  Female
3   Aryan   23    male

In [ ]:
#multiple conditions :

In [56]:
df[(df['Age'] >= 22) & ( df['Gender'] == 'Female')]

     Name  Age  Gender
2  Sakshi   22  Female

In [ ]:
# where method :

In [57]:
df.where(df['Age'] >= 22)

     Name   Age  Gender
0     NaN   NaN     NaN
1     Div  24.0    male
2  Sakshi  22.0  Female
3   Aryan  23.0    male

In [ ]:
#--> Using other attribute :

In [58]:
df.where(df['Age'] >= 22  , other = 'Not Eligible')

           Name           Age        Gender
0  Not Eligible  Not Eligible  Not Eligible
1           Div            24          male
2        Sakshi            22        Female
3         Aryan            23          male

In [59]:
# 6. Rows & Columns - Operation ( Add , update , delete)  :

In [60]:
df

      Name  Age  Gender
0  Anubhav   21    male
1      Div   24    male
2   Sakshi   22  Female
3    Aryan   23    male

In [63]:
#:--> Add new column : 

df['Team']  = ['CEO' , 'CTO' , 'HR' , 'DA']
df

df['Monthly_Salary'] = [45000 , 55000 , 65000 , 75000]
df

      Name  Age  Gender Team  Monthly_Salary
0  Anubhav   21    male  CEO           45000
1      Div   24    male  CTO           55000
2   Sakshi   22  Female   HR           65000
3    Aryan   23    male   DA           75000

In [ ]:
# :--> column by performing calculations :

In [65]:
df['Bonus'] = df['Monthly_Salary'] * 0.2
df

      Name  Age  Gender Team  Monthly_Salary    Bonus
0  Anubhav   21    male  CEO           45000   9000.0
1      Div   24    male  CTO           55000  11000.0
2   Sakshi   22  Female   HR           65000  13000.0
3    Aryan   23    male   DA           75000  15000.0

In [67]:
df['Total_Salary'] = df['Monthly_Salary'] + df['Bonus']
df

      Name  Age  Gender Team  Monthly_Salary    Bonus  Total_Salary
0  Anubhav   21    male  CEO           45000   9000.0       54000.0
1      Div   24    male  CTO           55000  11000.0       66000.0
2   Sakshi   22  Female   HR           65000  13000.0       78000.0
3    Aryan   23    male   DA           75000  15000.0       90000.0

In [ ]:
#:---->  Adding rows :

In [72]:
df.loc[len(df)] = ['Aditi' , 22 ,'Female' , 'Marketing' ,  66000 ,  4000 , 70000]
df

      Name  Age  Gender       Team  Monthly_Salary    Bonus  Total_Salary
0  Anubhav   21    male        CEO           45000   9000.0       54000.0
1      Div   24    male        CTO           55000  11000.0       66000.0
2   Sakshi   22  Female         HR           65000  13000.0       78000.0
3    Aryan   23    male         DA           75000  15000.0       90000.0
4    Aditi   22  Female  Marketing           66000   4000.0       70000.0

In [73]:
len(df)

5

In [79]:
# :--> update value :

df.loc[0 , 'Age'] = 22
df

      Name  Age  Gender       Team  Monthly_Salary    Bonus  Total_Salary
0  Anubhav   22    male        CEO           67000   9000.0       54000.0
1      Div   24    male        CTO           55000  11000.0       66000.0
2   Sakshi   22  Female         HR           65000  13000.0       78000.0
3    Aryan   23    male         DA           75000  15000.0       90000.0
4    Aditi   22  Female  Marketing           66000   4000.0       70000.0

In [80]:
df

      Name  Age  Gender       Team  Monthly_Salary    Bonus  Total_Salary
0  Anubhav   22    male        CEO           67000   9000.0       54000.0
1      Div   24    male        CTO           55000  11000.0       66000.0
2   Sakshi   22  Female         HR           65000  13000.0       78000.0
3    Aryan   23    male         DA           75000  15000.0       90000.0
4    Aditi   22  Female  Marketing           66000   4000.0       70000.0

In [ ]:
#-->  delete value : row[default] and columns value :

In [84]:
df = df.drop(df[df.Name == 'Aditi'].index) #--> drop row  , axis = 0 
df

      Name  Age  Gender Team  Monthly_Salary    Bonus  Total_Salary
0  Anubhav   22    male  CEO           67000   9000.0       54000.0
1      Div   24    male  CTO           55000  11000.0       66000.0
2   Sakshi   22  Female   HR           65000  13000.0       78000.0
3    Aryan   23    male   DA           75000  15000.0       90000.0

In [88]:
df = df.drop('Total_Salary' , axis = 1)
df

      Name  Age  Gender Team  Monthly_Salary
0  Anubhav   22    male  CEO           67000
1      Div   24    male  CTO           55000
2   Sakshi   22  Female   HR           65000
3    Aryan   23    male   DA           75000

In [ ]:
# :--> Sorting :

In [89]:
df.sort_values('Monthly_Salary')
# :--> Ascending order:

      Name  Age  Gender Team  Monthly_Salary
1      Div   24    male  CTO           55000
2   Sakshi   22  Female   HR           65000
0  Anubhav   22    male  CEO           67000
3    Aryan   23    male   DA           75000

In [ ]:
# :-> desecending order:

In [91]:
df.sort_values('Monthly_Salary' , ascending = False)

      Name  Age  Gender Team  Monthly_Salary
3    Aryan   23    male   DA           75000
0  Anubhav   22    male  CEO           67000
2   Sakshi   22  Female   HR           65000
1      Div   24    male  CTO           55000

In [ ]:
# 7. Working with date value :

In [ ]:
# 8. Handelling missing values

In [ ]:
# 9. Aggregation and group by

In [ ]:
# 10. Concatenate and Merge Dataframe ( JOINS )

In [ ]:
# 11. AI and ChatGPT